# Generated by Django 5.1.5 on 2026-01-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_mobiledevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('GENERAL_MANAGER', 'General Manager'), ('FINANCIAL_MANAGER', 'Financial Manager'), ('SUPERVISOR', 'Supervisor'), ('DATA_ENTRY', 'Data Entry'), ('RECEPTION', 'Reception'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
    ]
