# Generated by Django 5.1.5 on 2026-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESORT_ADMIN', 'Resort Admin'), ('GENERAL_MANAGER', 'General Manager'), ('FINANCIAL_MANAGER', 'Financial Manager'), ('SUPERVISOR', 'Supervisor'), ('DATA_ENTRY', 'Data Entry'), ('RECEPTION', 'Reception'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
    ]
