# Generated by Django 5.1.5 on 2026-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('RESORT_ADMIN', 'Resort Admin'), ('GENERAL_MANAGER', 'General Manager'), ('FINANCIAL_MANAGER', 'Financial Manager'), ('SUPERVISOR', 'Supervisor'), ('DATA_ENTRY', 'Data Entry'), ('RECEPTION', 'Reception'), ('SECURITY', 'Security'), ('RECREATION', 'Recreation'), ('OWNER', 'Owner'), ('TENANT', 'Tenant')], default='OWNER', max_length=20),
        ),
    ]
