# Generated by Django 5.1.5 on 2026-01-26 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_ownerunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for annual charges.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('SERVICES', 'Services'), ('ANNUAL_MAINTENANCE', 'Annual Maintenance'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_charges', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.resort')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['resort', 'status'], name='billing_cha_resort__1edfd1_idx'), models.Index(fields=['unit', 'status'], name='billing_cha_unit_id_57ce83_idx'), models.Index(fields=['year', 'month'], name='billing_cha_year_74be94_idx')],
            },
        ),
    ]
