# Generated by Django 5.1.5 on 2026-01-26 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0002_ownerunit'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charges', to='imports.excelupload'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('source_upload', 'source_row', 'type'), name='uniq_charge_per_upload_row_type'),
        ),
    ]
