# Generated by Django 5.1.5 on 2026-09-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentdeferral_paymentplan_paymentplaninstallment'),
        ('core', '0003_ownerunit_lease_start_date_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('as_of_date', models.DateField()),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_clear', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='clearance/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_statements', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_statements', to='core.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
