# Generated by Django 5.1.5 on 2026-09-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ownerunit_lease_start_date_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='resort_logos/'),
        ),
    ]
