# Generated by Django 5.1.5 on 2026-10-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resort_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_DEFERRED', 'Payment Deferred'), ('PAYMENT_PLAN_DECIDED', 'Payment Plan Decided'), ('CHARGE_PUBLISHED', 'Charges Published'), ('TICKET_REPLY', 'Support Reply'), ('UNIT_ACTIVITY', 'Unit Activity'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
