# Generated by Django 5.1.5 on 2026-10-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_charge_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_allowance', models.PositiveSmallIntegerField(help_text='Beach/pool access cards a unit of this type may hold at once.')),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='core.resort')),
            ],
            options={
                'ordering': ['resort', 'card_allowance', 'name'],
                'unique_together': {('resort', 'name')},
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.unittype'),
        ),
    ]
