# Generated by Django 5.1.5 on 2026-10-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='pass_issuance_mode',
            field=models.CharField(choices=[('APPROVAL', 'Security approves every pass request'), ('SELF_ISSUE', 'Owners issue their own passes')], default='APPROVAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_DEFERRED', 'Payment Deferred'), ('PAYMENT_PLAN_DECIDED', 'Payment Plan Decided'), ('CHARGE_PUBLISHED', 'Charges Published'), ('TICKET_REPLY', 'Support Reply'), ('TICKET_NEW', 'New Service Request'), ('TICKET_STATUS', 'Service Request Update'), ('PASS_REQUEST', 'New Pass Request'), ('PASS_DECIDED', 'Pass Request Decided'), ('UNIT_ACTIVITY', 'Unit Activity'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
