# Generated by Django 5.1.5 on 2026-10-06 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resort_pass_issuance_mode_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerunit',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_DEFERRED', 'Payment Deferred'), ('PAYMENT_PLAN_DECIDED', 'Payment Plan Decided'), ('CHARGE_PUBLISHED', 'Charges Published'), ('TICKET_REPLY', 'Support Reply'), ('TICKET_NEW', 'New Service Request'), ('TICKET_STATUS', 'Service Request Update'), ('PASS_REQUEST', 'New Pass Request'), ('PASS_DECIDED', 'Pass Request Decided'), ('UNIT_ACTIVITY', 'Unit Activity'), ('LEASE_REGISTERED', 'Unit Rented Out'), ('LEASE_ENDED', 'Rental Ended'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('SHORT', 'Short stay'), ('LONG', 'Long-term (utilities move to the tenant)')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_phone', models.CharField(max_length=20)),
                ('tenant_national_id', models.CharField(max_length=50, verbose_name='Tenant national ID / passport')),
                ('tenant_id_photo', models.FileField(upload_to='lease_ids/')),
                ('occupants', models.PositiveSmallIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_given', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.resort')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_taken', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.unit')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['unit', 'start_date', 'end_date'], name='core_lease_unit_id_e18685_idx')],
            },
        ),
    ]
