# Generated by Django 5.1.5 on 2026-10-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lease_and_lease_end_date'),
        ('support', '0008_alter_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='access_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support.visitorpass'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_DEFERRED', 'Payment Deferred'), ('PAYMENT_PLAN_DECIDED', 'Payment Plan Decided'), ('CHARGE_PUBLISHED', 'Charges Published'), ('TICKET_REPLY', 'Support Reply'), ('TICKET_NEW', 'New Service Request'), ('TICKET_STATUS', 'Service Request Update'), ('PASS_REQUEST', 'New Pass Request'), ('PASS_DECIDED', 'Pass Request Decided'), ('UNIT_ACTIVITY', 'Unit Activity'), ('LEASE_REGISTERED', 'Unit Rented Out'), ('LEASE_ENDED', 'Rental Ended'), ('LEASE_UPDATED', 'Rental Updated'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='LeaseAdult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=50, verbose_name='National ID / passport')),
                ('id_photo', models.FileField(upload_to='lease_ids/')),
                ('relation', models.CharField(choices=[('SPOUSE', 'Spouse'), ('FAMILY', 'Family member'), ('OTHER', 'Other adult')], default='SPOUSE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support.visitorpass')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='core.lease')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MARRIAGE_CERT', 'Marriage certificate'), ('PASSPORT', 'Passport'), ('OTHER', 'Other document')], max_length=15)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='lease_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.lease')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
