# Generated by Django 5.1.5 on 2026-10-07 00:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lease_adults_documents_access_pass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_DEFERRED', 'Payment Deferred'), ('PAYMENT_PLAN_DECIDED', 'Payment Plan Decided'), ('CHARGE_PUBLISHED', 'Charges Published'), ('TICKET_REPLY', 'Support Reply'), ('TICKET_NEW', 'New Service Request'), ('TICKET_STATUS', 'Service Request Update'), ('PASS_REQUEST', 'New Pass Request'), ('PASS_DECIDED', 'Pass Request Decided'), ('UNIT_ACTIVITY', 'Unit Activity'), ('LEASE_REGISTERED', 'Unit Rented Out'), ('LEASE_ENDED', 'Rental Ended'), ('LEASE_UPDATED', 'Rental Updated'), ('METER_READING_DUE', 'Meter Reading Due'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER', 'Water')], max_length=12)),
                ('kind', models.CharField(choices=[('ENTRY', 'At entry'), ('EXIT', 'At exit'), ('REGULAR', 'Regular reading')], default='REGULAR', max_length=8)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('read_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to='core.lease')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings_taken', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='core.resort')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='core.unit')),
            ],
            options={
                'ordering': ['-read_on', '-id'],
                'indexes': [models.Index(fields=['unit', 'meter', 'read_on'], name='core_meterr_unit_id_30d10f_idx')],
            },
        ),
    ]
