# Generated by Django 5.1.5 on 2026-01-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_ownerunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('EXCEL_UPLOAD', 'Excel Upload')], default='EXCEL_UPLOAD', max_length=30)),
                ('format_type', models.CharField(choices=[('LONG', 'Row per charge (long)'), ('WIDE', 'Row per unit (wide)')], max_length=10)),
                ('mapping', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='core.resort')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='UPLOADED', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_uploads', to='core.resort')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='imports.importsource')),
            ],
        ),
    ]
