# Generated by Django 5.1.5 on 2026-01-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsource',
            name='format_type',
            field=models.CharField(choices=[('LONG', 'Row per charge (long)'), ('WIDE', 'Row per unit (wide)')], default='WIDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='mapping',
            field=models.JSONField(default=dict, help_text='Mapping configuration for columns'),
        ),
    ]
