# Generated by Django 5.1.5 on 2026-09-18 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownerunit'),
        ('support', '0002_alter_ticket_options_message_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('VISITOR', 'Visitor Access'), ('TENANT', 'Tenant Access'), ('BEACH_ACCESS', 'Beach Access'), ('MAINTENANCE_WORKER', 'Maintenance Worker')], default='VISITOR', max_length=20)),
                ('visitor_name', models.CharField(max_length=255)),
                ('national_id_or_passport', models.CharField(blank=True, default='', max_length=50)),
                ('car_plate', models.CharField(blank=True, default='', max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('pass_code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='core.resort')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_passes', to='core.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
