# Generated by Django 5.1.5 on 2026-10-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unit_type'),
        ('support', '0003_visitorpass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(max_length=64)),
                ('point', models.CharField(choices=[('GATE', 'Security Gate'), ('BEACH_POOL', 'Beach / Pool')], max_length=12)),
                ('result', models.CharField(choices=[('GRANTED', 'Granted'), ('DENIED', 'Denied')], max_length=10)),
                ('deny_reason', models.CharField(blank=True, choices=[('NOT_FOUND', 'Unknown pass'), ('CANCELLED', 'Pass cancelled'), ('EXPIRED', 'Pass expired'), ('NOT_YET_VALID', 'Pass not valid yet'), ('WRONG_PASS_TYPE', 'Not a beach/pool card')], default='', max_length=20)),
                ('towels_issued', models.PositiveSmallIntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_scans', to='core.resort')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_scans', to=settings.AUTH_USER_MODEL)),
                ('visitor_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='support.visitorpass')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['resort', 'point', 'scanned_at'], name='support_pas_resort__e7bcce_idx'), models.Index(fields=['visitor_pass', 'scanned_at'], name='support_pas_visitor_741258_idx')],
            },
        ),
    ]
