# Generated by Django 5.1.5 on 2026-10-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_type'),
        ('support', '0004_passscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passscan',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(blank=True, choices=[('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter'), ('SATELLITE', 'Satellite Technician'), ('GARDENING', 'Gardening & Agriculture'), ('PEST_CONTROL', 'Pest Control'), ('HOUSEKEEPING', 'Housekeeping')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter'), ('SATELLITE', 'Satellite Technician'), ('GARDENING', 'Gardening & Agriculture'), ('PEST_CONTROL', 'Pest Control'), ('HOUSEKEEPING', 'Housekeeping')], max_length=20)),
                ('assignee', models.ForeignKey(help_text='Staff member who receives these requests.', on_delete=django.db.models.deletion.CASCADE, related_name='service_routes', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_routes', to='core.resort')),
            ],
            options={
                'ordering': ['resort', 'service_type'],
                'unique_together': {('resort', 'service_type')},
            },
        ),
    ]
