# Generated by Django 5.1.5 on 2026-10-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_passscan_device_label_ticket_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='passscan',
            name='deny_reason',
            field=models.CharField(blank=True, choices=[('NOT_FOUND', 'Unknown pass'), ('CANCELLED', 'Pass cancelled'), ('EXPIRED', 'Pass expired'), ('NOT_YET_VALID', 'Pass not valid yet'), ('WRONG_PASS_TYPE', 'Not a beach/pool card'), ('PENDING_APPROVAL', 'Not approved by Security yet'), ('REJECTED', 'Request rejected')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15),
        ),
    ]
