# Generated by Django 5.1.5 on 2026-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_visitorpass_decided_at_visitorpass_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='technician_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='ServiceRoute',
        ),
    ]
