# Generated by Django 5.1.5 on 2026-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_ticket_technician_name_delete_serviceroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the issue'),
        ),
    ]
