# Generated by Django 5.1.5 on 2026-10-05 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UNIT_FOR_SALE', 'Unit for Sale'), ('UNIT_FOR_RENT', 'Unit for Rent'), ('EVENT', 'Event'), ('NOTICE', 'Notice')], default='NOTICE', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='EGP. For unit listings; leave empty for "price on request".', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('event_date', models.DateTimeField(blank=True, help_text='Required for events.', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Hidden from the app after this time. Events with no value here stay up until the day after the event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.resort')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['resort', 'is_published', 'published_at'], name='announcemen_resort__e997a7_idx')],
            },
        ),
    ]
