# Generated by Django 5.1.5 on 2026-07-27 01:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
        ('core', '0002_ownerunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('_charge_ids_json', models.TextField(db_column='charge_ids_json', help_text='JSON array of billing.Charge PKs committed to this session.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Payment Session',
                'verbose_name_plural': 'Payment Sessions',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['unit', 'paid_at'], name='collections_unit_id_9a7e39_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['resort', 'paid_at'], name='collections_resort__40563b_idx'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='core.resort'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='core.unit'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['merchant_order_id'], name='collections_merchan_5d7d13_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['owner', 'status'], name='collections_owner_i_343f0b_idx'),
        ),
    ]
