# Generated by Django 5.1.5 on 2026-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_add_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
