# Generated by Django 5.1.5 on 2026-09-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_payment_receipt_pdf'),
        ('core', '0003_ownerunit_lease_start_date_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='remaining_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='core.unit'),
        ),
    ]
