# Generated by Django 5.1.5 on 2026-10-07 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0005_payment_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CARD', 'Bank card'), ('WALLET', 'Mobile wallet'), ('INSTAPAY', 'InstaPay'), ('FAWRY', 'Fawry')], max_length=10)),
                ('label', models.CharField(max_length=120)),
                ('wallet_provider', models.CharField(blank=True, choices=[('VODAFONE_CASH', 'Vodafone Cash'), ('ORANGE_CASH', 'Orange Cash'), ('ETISALAT_CASH', 'Etisalat Cash'), ('WE_PAY', 'WE Pay'), ('OTHER', 'Other wallet')], default='', max_length=15)),
                ('wallet_phone', models.CharField(blank=True, default='', max_length=20)),
                ('instapay_address', models.CharField(blank=True, default='', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
