# Generated by Django 5.1.5 on 2026-03-30 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownerunit'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.resort'),
        ),
    ]
