/// Strings for the profile, "My units" and rent-out screens.
///
/// Kept apart from the main table (a 2000-line file already) and consulted by
/// [AppLocalizations.translate] after it. Covers en, ar, de, fr, it and ru;
/// every other language falls back to English for these screens, exactly as
/// it does for any key it doesn't have. `%s` / `%d` are filled in by the
/// screens.
const Map<String, Map<String, String>> kProfileStrings = {
  'en': {
    'profile_edit_name': 'Edit name',
    'profile_my_units': 'My units',
    'profile_no_units': 'No units are linked to your account yet.',
    'unit_count_one': '1 unit',
    'unit_count_two': '2 units',
    'unit_count_many': '%d units',
    'profile_unit_type': 'Type',
    'profile_unit_cards': 'Access cards',
    'rent_out_button': 'Rent out',
    'rent_out_title': 'Rent out unit',
    'rent_term_label': 'Type of rental',
    'rent_term_short': 'Short stay',
    'rent_term_long': 'Long-term',
    'rent_term_short_hint':
        "The tenant is only registered with the village. Water and electricity stay on your account.",
    'rent_term_long_hint':
        "The tenant gets an account. Water and electricity for these months are charged to the tenant, not to you.",
    'rent_start_date': 'Starts',
    'rent_end_date': 'Ends',
    'rent_tenant_section': 'Tenant details',
    'rent_tenant_name': "Tenant's full name",
    'rent_tenant_phone': "Tenant's phone number",
    'rent_tenant_phone_hint': 'The tenant signs in to the app with this number.',
    'rent_tenant_id': 'National ID / Passport number',
    'rent_id_photo': 'ID / Passport photo',
    'rent_id_photo_add': 'Add photo',
    'rent_id_photo_change': 'Change photo',
    'rent_id_photo_camera': 'Take a photo',
    'rent_id_photo_gallery': 'Choose from gallery',
    'rent_occupants': 'Number of occupants',
    'rent_village_note':
        "The village is notified automatically — no approval needed. When you request pool/beach cards for this unit, Security will see that it is rented.",
    'rent_submit': 'Register rental',
    'rent_confirm_title': 'Move water & electricity to the tenant?',
    'rent_confirm_body':
        "From %s to %s, water and electricity charges for this unit go to the tenant's account and disappear from yours. Anything unpaid comes back to you after the rental ends.",
    'rent_confirm_ok': 'Confirm',
    'rent_registered': 'Rental registered. The village has been notified.',
    'rent_status_active': 'Rented',
    'rent_status_upcoming': 'Upcoming',
    'rent_status_ended': 'Ended',
    'rent_rented_to': 'Rented to %s',
    'lease_details_title': 'Rental details',
    'lease_tenant': 'Tenant',
    'lease_tenant_phone': 'Phone',
    'lease_tenant_id': 'ID / Passport',
    'lease_period': 'Period',
    'lease_term': 'Type',
    'lease_occupants': 'Occupants',
    'lease_tenant_balance': 'Tenant still owes',
    'lease_tenant_cleared': 'The tenant has paid everything — clearance statement available',
    'lease_end_button': 'End rental',
    'lease_end_confirm_title': 'End this rental?',
    'lease_end_confirm_body':
        "Water and electricity go back to your account from this month. The tenant can still pay what they owe for their own months and get their clearance statement.",
    'lease_ended_done': 'Rental ended.',
    'tenant_lease_line': 'Lease period: %s – %s',
    'tenant_lease_ended_hint': 'Your lease has ended. Pay what is left to get your clearance statement.',

    'rent_adults_section': 'Adults staying',
    'rent_adults_hint':
        "Every adult gets their own QR for the village gate and the pool. Add the tenant's spouse and any other adult, each with a photo of their ID or passport.",
    'rent_add_adult': 'Add an adult',
    'adult_form_title': 'Add an adult',
    'adult_name': 'Full name',
    'adult_id_number': 'National ID / Passport number',
    'adult_id_photo': 'ID / Passport photo',
    'adult_relation_label': 'Relation to the tenant',
    'adult_relation_spouse': 'Spouse',
    'adult_relation_family': 'Family member',
    'adult_relation_other': 'Other adult',
    'rent_docs_section': 'Papers for Security',
    'rent_docs_hint':
        "Marriage certificate, passports… They go to the village's Security so your tenant is registered and their QR is recognised.",
    'rent_add_document': 'Add a paper',
    'doc_kind_marriage': 'Marriage certificate',
    'doc_kind_passport': 'Passport',
    'doc_kind_other': 'Other paper',
    'doc_label_hint': 'Whose is it? (optional)',
    'rent_uploads_failed': 'Rental registered, but %s upload(s) failed. Add them again from the rental details.',
    'rent_max_adults': 'This unit has room for %s adults, the tenant included.',
    'lease_qr_section': 'QR codes — village gate & pool',
    'lease_qr_tenant': 'Tenant',
    'lease_qr_show': 'Show QR',
    'lease_qr_short_hint':
        "A short stay has no app account. Show or send these QR codes to your guests — they open the village gate and the pool.",
    'lease_valid_until': 'Valid until %s',
    'lease_adults_section': 'Adults',
    'lease_add_adult': 'Add an adult',
    'lease_remove_adult_confirm': 'Remove %s? Their QR stops working.',
    'lease_remove': 'Remove',
    'lease_docs_section': 'Papers',
    'lease_remove_doc_confirm': 'Remove this paper?',
    'lease_extend_button': 'Extend',
    'lease_extend_title': 'Extend the rental until',
    'lease_extended_done': 'Rental extended. The QR codes stay valid.',
    'lease_renew_button': 'New period',
    'lease_renew_title': 'Renew the rental',
    'lease_renew_hint': 'Same tenant, same people and the same QR codes — only the dates change.',
    'lease_renewed_done': 'New rental period registered. The QR codes stay valid.',
    'stay_title': 'Your stay',
    'stay_qr_hint': 'Show these QR codes at the village gate and the pool.',
    'meter_section': 'Meter readings',
    'meter_hint': "Read by the village's Maintenance team when the stay starts and when it ends.",
    'meter_electricity': 'Electricity',
    'meter_water': 'Water',
    'meter_entry': 'At entry',
    'meter_exit': 'At exit',
    'meter_pending': 'Not read yet',
    'pm_empty': 'No saved payment methods yet.',
    'pm_intro':
        "Save how you like to pay. Card details are never kept in this app — cards are entered in the payment provider's own secure form.",
    'pm_add': 'Add payment method',
    'pm_default': 'Default',
    'pm_make_default': 'Make default',
    'pm_remove': 'Remove',
    'pm_remove_confirm': 'Remove %s?',
    'pm_card': 'Bank card (Visa, Mastercard, Meeza)',
    'pm_card_soon':
        "Available once online payment goes live. You will enter it in the provider's secure form, never here.",
    'pm_wallet': 'Mobile wallet',
    'pm_wallet_hint': 'Vodafone Cash, Orange Cash, Etisalat Cash, WE Pay',
    'pm_wallet_provider': 'Wallet',
    'pm_wallet_phone': 'Wallet phone number',
    'pm_instapay': 'InstaPay',
    'pm_instapay_hint': 'Pay from your bank account with your InstaPay address',
    'pm_instapay_address': 'InstaPay address (e.g. name@instapay)',
    'pm_fawry': 'Fawry',
    'pm_fawry_hint': 'Pay with a Fawry reference at any Fawry outlet',
    'pm_saved': 'Payment method saved.',
    'pm_removed': 'Payment method removed.',
    'pm_full': 'You have saved the most payment methods allowed. Remove one to add another.',
  },
  'ar': {
    'profile_edit_name': 'تعديل الاسم',
    'profile_my_units': 'وحداتي',
    'profile_no_units': 'لا توجد وحدات مرتبطة بحسابك حتى الآن.',
    'unit_count_one': 'وحدة واحدة',
    'unit_count_two': 'وحدتان',
    'unit_count_many': '%d وحدات',
    'profile_unit_type': 'نوع الوحدة',
    'profile_unit_cards': 'كروت الدخول',
    'rent_out_button': 'تأجير الوحدة',
    'rent_out_title': 'تأجير وحدة',
    'rent_term_label': 'نوع الإيجار',
    'rent_term_short': 'إقامة قصيرة',
    'rent_term_long': 'إيجار طويل',
    'rent_term_short_hint': 'يُسجَّل المستأجر لدى القرية فقط، وتبقى استهلاكات المياه والكهرباء على حسابك.',
    'rent_term_long_hint':
        'يُنشأ للمستأجر حساب على التطبيق، وتُحوَّل استهلاكات المياه والكهرباء عن فترة الإيجار إلى حسابه بدلاً من حسابك.',
    'rent_start_date': 'بداية الإيجار',
    'rent_end_date': 'نهاية الإيجار',
    'rent_tenant_section': 'بيانات المستأجر',
    'rent_tenant_name': 'اسم المستأجر بالكامل',
    'rent_tenant_phone': 'رقم موبايل المستأجر',
    'rent_tenant_phone_hint': 'يسجّل المستأجر دخوله إلى التطبيق بهذا الرقم.',
    'rent_tenant_id': 'رقم البطاقة / جواز السفر',
    'rent_id_photo': 'صورة البطاقة / جواز السفر',
    'rent_id_photo_add': 'إضافة صورة',
    'rent_id_photo_change': 'تغيير الصورة',
    'rent_id_photo_camera': 'التقاط صورة',
    'rent_id_photo_gallery': 'اختيار من المعرض',
    'rent_occupants': 'عدد الأفراد',
    'rent_village_note':
        'تُبلَّغ القرية تلقائياً دون الحاجة إلى موافقة. وعند طلبك كروت المسبح أو الشاطئ لهذه الوحدة، سيرى أمن القرية أن الوحدة مؤجَّرة.',
    'rent_submit': 'تسجيل الإيجار',
    'rent_confirm_title': 'تحويل المياه والكهرباء إلى المستأجر؟',
    'rent_confirm_body':
        'من %s إلى %s ستُحتسب استهلاكات المياه والكهرباء لهذه الوحدة على حساب المستأجر وتختفي من حسابك. وما لم يسدّده المستأجر يعود إليك بعد انتهاء الإيجار.',
    'rent_confirm_ok': 'تأكيد',
    'rent_registered': 'تم تسجيل الإيجار وإبلاغ القرية.',
    'rent_status_active': 'مؤجَّرة',
    'rent_status_upcoming': 'إيجار قادم',
    'rent_status_ended': 'انتهى الإيجار',
    'rent_rented_to': 'مؤجَّرة لـ %s',
    'lease_details_title': 'تفاصيل الإيجار',
    'lease_tenant': 'المستأجر',
    'lease_tenant_phone': 'رقم الموبايل',
    'lease_tenant_id': 'رقم البطاقة / الجواز',
    'lease_period': 'مدة الإيجار',
    'lease_term': 'النوع',
    'lease_occupants': 'عدد الأفراد',
    'lease_tenant_balance': 'المتبقي على المستأجر',
    'lease_tenant_cleared': 'سدّد المستأجر كل المستحقات — مخالصة نهاية العقد متاحة له',
    'lease_end_button': 'إنهاء الإيجار',
    'lease_end_confirm_title': 'إنهاء هذا الإيجار؟',
    'lease_end_confirm_body':
        'تعود استهلاكات المياه والكهرباء إلى حسابك من هذا الشهر. ويظل بإمكان المستأجر سداد ما عليه عن فترته والحصول على مخالصة نهاية العقد.',
    'lease_ended_done': 'تم إنهاء الإيجار.',
    'tenant_lease_line': 'مدة الإيجار: %s – %s',
    'tenant_lease_ended_hint': 'انتهى إيجارك. سدّد ما تبقّى عليك لتحصل على مخالصة نهاية العقد.',

    'rent_adults_section': 'البالغون المقيمون',
    'rent_adults_hint':
        'يحصل كل بالغ على QR خاص به لبوابة القرية وحمام السباحة. أضف زوج/زوجة المستأجر وأي بالغ آخر، مع صورة بطاقة كل منهم أو جواز سفره.',
    'rent_add_adult': 'إضافة بالغ',
    'adult_form_title': 'إضافة بالغ',
    'adult_name': 'الاسم بالكامل',
    'adult_id_number': 'رقم البطاقة / جواز السفر',
    'adult_id_photo': 'صورة البطاقة / جواز السفر',
    'adult_relation_label': 'صلته بالمستأجر',
    'adult_relation_spouse': 'زوج/زوجة',
    'adult_relation_family': 'من العائلة',
    'adult_relation_other': 'بالغ آخر',
    'rent_docs_section': 'أوراق للأمن',
    'rent_docs_hint':
        'قسيمة الزواج، جوازات السفر… تصل إلى أمن القرية ليُسجَّل المستأجر ويُقرأ الـ QR الخاص به.',
    'rent_add_document': 'إضافة ورقة',
    'doc_kind_marriage': 'قسيمة الزواج',
    'doc_kind_passport': 'جواز سفر',
    'doc_kind_other': 'ورقة أخرى',
    'doc_label_hint': 'خاصة بمن؟ (اختياري)',
    'rent_uploads_failed': 'تم تسجيل الإيجار، لكن فشل رفع %s ملف. أضفها مرة أخرى من تفاصيل الإيجار.',
    'rent_max_adults': 'تتّسع هذه الوحدة لـ %s بالغين بمن فيهم المستأجر.',
    'lease_qr_section': 'أكواد QR — بوابة القرية وحمام السباحة',
    'lease_qr_tenant': 'المستأجر',
    'lease_qr_show': 'عرض الـ QR',
    'lease_qr_short_hint':
        'الإقامة القصيرة ليس لها حساب على التطبيق. اعرض أكواد QR هذه على ضيوفك أو أرسلها إليهم — تفتح لهم بوابة القرية وحمام السباحة.',
    'lease_valid_until': 'صالح حتى %s',
    'lease_adults_section': 'البالغون',
    'lease_add_adult': 'إضافة بالغ',
    'lease_remove_adult_confirm': 'حذف %s؟ سيتوقف الـ QR الخاص به عن العمل.',
    'lease_remove': 'حذف',
    'lease_docs_section': 'الأوراق',
    'lease_remove_doc_confirm': 'حذف هذه الورقة؟',
    'lease_extend_button': 'تمديد',
    'lease_extend_title': 'تمديد الإيجار حتى',
    'lease_extended_done': 'تم تمديد الإيجار. تظل أكواد QR صالحة.',
    'lease_renew_button': 'مدة جديدة',
    'lease_renew_title': 'تجديد الإيجار',
    'lease_renew_hint': 'نفس المستأجر ونفس الأفراد ونفس أكواد QR — تتغير التواريخ فقط.',
    'lease_renewed_done': 'تم تسجيل مدة إيجار جديدة. تظل أكواد QR صالحة.',
    'stay_title': 'إقامتك',
    'stay_qr_hint': 'اعرض أكواد QR هذه عند بوابة القرية وحمام السباحة.',
    'meter_section': 'قراءات العدادات',
    'meter_hint': 'يسجّلها فريق الصيانة بالقرية عند بداية الإقامة وعند نهايتها.',
    'meter_electricity': 'الكهرباء',
    'meter_water': 'المياه',
    'meter_entry': 'عند الدخول',
    'meter_exit': 'عند الخروج',
    'meter_pending': 'لم تُقرأ بعد',
    'pm_empty': 'لا توجد طرق دفع محفوظة بعد.',
    'pm_intro':
        'احفظ الطريقة التي تفضّل الدفع بها. لا تُحفظ بيانات الكروت داخل هذا التطبيق — تُدخل في نموذج مزوّد الدفع الآمن الخاص به.',
    'pm_add': 'إضافة طريقة دفع',
    'pm_default': 'الافتراضية',
    'pm_make_default': 'تعيين كافتراضية',
    'pm_remove': 'حذف',
    'pm_remove_confirm': 'حذف %s؟',
    'pm_card': 'كارت بنكي (فيزا، ماستركارد، ميزة)',
    'pm_card_soon':
        'يُتاح عند تشغيل الدفع الإلكتروني. ستُدخله في نموذج مزوّد الدفع الآمن وليس هنا أبداً.',
    'pm_wallet': 'محفظة إلكترونية',
    'pm_wallet_hint': 'فودافون كاش، أورانج كاش، اتصالات كاش، WE Pay',
    'pm_wallet_provider': 'المحفظة',
    'pm_wallet_phone': 'رقم موبايل المحفظة',
    'pm_instapay': 'إنستا باي',
    'pm_instapay_hint': 'الدفع من حسابك البنكي بعنوان إنستا باي الخاص بك',
    'pm_instapay_address': 'عنوان إنستا باي (مثال: name@instapay)',
    'pm_fawry': 'فوري',
    'pm_fawry_hint': 'الدفع برقم مرجعي من أي منفذ فوري',
    'pm_saved': 'تم حفظ طريقة الدفع.',
    'pm_removed': 'تم حذف طريقة الدفع.',
    'pm_full': 'وصلت إلى الحد الأقصى لطرق الدفع المحفوظة. احذف واحدة لإضافة أخرى.',
  },
  'de': {
    'profile_edit_name': 'Namen bearbeiten',
    'profile_my_units': 'Meine Einheiten',
    'profile_no_units': 'Ihrem Konto sind noch keine Einheiten zugeordnet.',
    'unit_count_one': '1 Einheit',
    'unit_count_two': '2 Einheiten',
    'unit_count_many': '%d Einheiten',
    'profile_unit_type': 'Typ',
    'profile_unit_cards': 'Zugangskarten',
    'rent_out_button': 'Vermieten',
    'rent_out_title': 'Einheit vermieten',
    'rent_term_label': 'Art der Vermietung',
    'rent_term_short': 'Kurzaufenthalt',
    'rent_term_long': 'Langzeitmiete',
    'rent_term_short_hint':
        'Der Mieter wird nur beim Dorf registriert. Wasser und Strom bleiben auf Ihrem Konto.',
    'rent_term_long_hint':
        'Der Mieter erhält ein Konto. Wasser und Strom für diese Monate werden dem Mieter berechnet, nicht Ihnen.',
    'rent_start_date': 'Beginn',
    'rent_end_date': 'Ende',
    'rent_tenant_section': 'Angaben zum Mieter',
    'rent_tenant_name': 'Vollständiger Name des Mieters',
    'rent_tenant_phone': 'Telefonnummer des Mieters',
    'rent_tenant_phone_hint': 'Der Mieter meldet sich mit dieser Nummer in der App an.',
    'rent_tenant_id': 'Ausweis-/Reisepassnummer',
    'rent_id_photo': 'Foto von Ausweis / Reisepass',
    'rent_id_photo_add': 'Foto hinzufügen',
    'rent_id_photo_change': 'Foto ändern',
    'rent_id_photo_camera': 'Foto aufnehmen',
    'rent_id_photo_gallery': 'Aus der Galerie wählen',
    'rent_occupants': 'Anzahl der Bewohner',
    'rent_village_note':
        'Das Dorf wird automatisch benachrichtigt – eine Genehmigung ist nicht nötig. Wenn Sie Pool-/Strandkarten für diese Einheit anfordern, sieht der Sicherheitsdienst, dass sie vermietet ist.',
    'rent_submit': 'Vermietung registrieren',
    'rent_confirm_title': 'Wasser und Strom auf den Mieter übertragen?',
    'rent_confirm_body':
        'Von %s bis %s werden Wasser- und Stromkosten dieser Einheit dem Konto des Mieters belastet und verschwinden von Ihrem. Offene Beträge fallen nach Mietende an Sie zurück.',
    'rent_confirm_ok': 'Bestätigen',
    'rent_registered': 'Vermietung registriert. Das Dorf wurde benachrichtigt.',
    'rent_status_active': 'Vermietet',
    'rent_status_upcoming': 'Bevorstehend',
    'rent_status_ended': 'Beendet',
    'rent_rented_to': 'Vermietet an %s',
    'lease_details_title': 'Mietdetails',
    'lease_tenant': 'Mieter',
    'lease_tenant_phone': 'Telefon',
    'lease_tenant_id': 'Ausweis / Reisepass',
    'lease_period': 'Zeitraum',
    'lease_term': 'Art',
    'lease_occupants': 'Bewohner',
    'lease_tenant_balance': 'Mieter schuldet noch',
    'lease_tenant_cleared': 'Der Mieter hat alles bezahlt – Unbedenklichkeitsbescheinigung verfügbar',
    'lease_end_button': 'Miete beenden',
    'lease_end_confirm_title': 'Diese Miete beenden?',
    'lease_end_confirm_body':
        'Wasser und Strom gehen ab diesem Monat wieder auf Ihr Konto. Der Mieter kann seine eigenen Monate weiterhin begleichen und seine Unbedenklichkeitsbescheinigung erhalten.',
    'lease_ended_done': 'Miete beendet.',
    'tenant_lease_line': 'Mietzeit: %s – %s',
    'tenant_lease_ended_hint':
        'Ihre Miete ist beendet. Begleichen Sie den Rest, um Ihre Unbedenklichkeitsbescheinigung zu erhalten.',

    'rent_adults_section': 'Anwesende Erwachsene',
    'rent_adults_hint':
        'Jeder Erwachsene erhält einen eigenen QR-Code für das Dorftor und den Pool. Fügen Sie Ehepartner und weitere Erwachsene hinzu, jeweils mit Foto von Ausweis oder Reisepass.',
    'rent_add_adult': 'Erwachsenen hinzufügen',
    'adult_form_title': 'Erwachsenen hinzufügen',
    'adult_name': 'Vollständiger Name',
    'adult_id_number': 'Ausweis-/Reisepassnummer',
    'adult_id_photo': 'Foto von Ausweis / Reisepass',
    'adult_relation_label': 'Beziehung zum Mieter',
    'adult_relation_spouse': 'Ehepartner',
    'adult_relation_family': 'Familienmitglied',
    'adult_relation_other': 'Anderer Erwachsener',
    'rent_docs_section': 'Unterlagen für den Sicherheitsdienst',
    'rent_docs_hint':
        'Heiratsurkunde, Reisepässe … Sie gehen an den Sicherheitsdienst des Dorfes, damit der Mieter registriert ist und sein QR-Code erkannt wird.',
    'rent_add_document': 'Unterlage hinzufügen',
    'doc_kind_marriage': 'Heiratsurkunde',
    'doc_kind_passport': 'Reisepass',
    'doc_kind_other': 'Andere Unterlage',
    'doc_label_hint': 'Von wem? (optional)',
    'rent_uploads_failed':
        'Vermietung registriert, aber %s Upload(s) sind fehlgeschlagen. Fügen Sie sie in den Mietdetails erneut hinzu.',
    'rent_max_adults': 'Diese Einheit bietet Platz für %s Erwachsene, den Mieter eingeschlossen.',
    'lease_qr_section': 'QR-Codes — Dorftor & Pool',
    'lease_qr_tenant': 'Mieter',
    'lease_qr_show': 'QR anzeigen',
    'lease_qr_short_hint':
        'Ein Kurzaufenthalt hat kein App-Konto. Zeigen oder senden Sie diese QR-Codes Ihren Gästen — sie öffnen das Dorftor und den Pool.',
    'lease_valid_until': 'Gültig bis %s',
    'lease_adults_section': 'Erwachsene',
    'lease_add_adult': 'Erwachsenen hinzufügen',
    'lease_remove_adult_confirm': '%s entfernen? Der QR-Code wird ungültig.',
    'lease_remove': 'Entfernen',
    'lease_docs_section': 'Unterlagen',
    'lease_remove_doc_confirm': 'Diese Unterlage entfernen?',
    'lease_extend_button': 'Verlängern',
    'lease_extend_title': 'Miete verlängern bis',
    'lease_extended_done': 'Miete verlängert. Die QR-Codes bleiben gültig.',
    'lease_renew_button': 'Neuer Zeitraum',
    'lease_renew_title': 'Miete erneuern',
    'lease_renew_hint': 'Gleicher Mieter, gleiche Personen, gleiche QR-Codes — nur die Daten ändern sich.',
    'lease_renewed_done': 'Neuer Mietzeitraum registriert. Die QR-Codes bleiben gültig.',
    'stay_title': 'Ihr Aufenthalt',
    'stay_qr_hint': 'Zeigen Sie diese QR-Codes am Dorftor und am Pool.',
    'meter_section': 'Zählerstände',
    'meter_hint': 'Vom Wartungsteam des Dorfes bei Beginn und Ende des Aufenthalts abgelesen.',
    'meter_electricity': 'Strom',
    'meter_water': 'Wasser',
    'meter_entry': 'Bei Einzug',
    'meter_exit': 'Bei Auszug',
    'meter_pending': 'Noch nicht abgelesen',
    'pm_empty': 'Noch keine Zahlungsarten gespeichert.',
    'pm_intro':
        'Speichern Sie, wie Sie gern bezahlen. Kartendaten werden in dieser App nie gespeichert — Karten werden im sicheren Formular des Zahlungsanbieters eingegeben.',
    'pm_add': 'Zahlungsart hinzufügen',
    'pm_default': 'Standard',
    'pm_make_default': 'Als Standard festlegen',
    'pm_remove': 'Entfernen',
    'pm_remove_confirm': '%s entfernen?',
    'pm_card': 'Bankkarte (Visa, Mastercard, Meeza)',
    'pm_card_soon':
        'Verfügbar, sobald die Online-Zahlung startet. Sie geben sie im sicheren Formular des Anbieters ein, nie hier.',
    'pm_wallet': 'Mobile Wallet',
    'pm_wallet_hint': 'Vodafone Cash, Orange Cash, Etisalat Cash, WE Pay',
    'pm_wallet_provider': 'Wallet',
    'pm_wallet_phone': 'Telefonnummer der Wallet',
    'pm_instapay': 'InstaPay',
    'pm_instapay_hint': 'Von Ihrem Bankkonto mit Ihrer InstaPay-Adresse bezahlen',
    'pm_instapay_address': 'InstaPay-Adresse (z. B. name@instapay)',
    'pm_fawry': 'Fawry',
    'pm_fawry_hint': 'Mit einer Fawry-Referenz an jeder Fawry-Stelle bezahlen',
    'pm_saved': 'Zahlungsart gespeichert.',
    'pm_removed': 'Zahlungsart entfernt.',
    'pm_full': 'Sie haben die maximale Zahl an Zahlungsarten gespeichert. Entfernen Sie eine, um eine neue hinzuzufügen.',
  },
  'fr': {
    'profile_edit_name': 'Modifier le nom',
    'profile_my_units': 'Mes unités',
    'profile_no_units': "Aucune unité n'est encore liée à votre compte.",
    'unit_count_one': '1 unité',
    'unit_count_two': '2 unités',
    'unit_count_many': '%d unités',
    'profile_unit_type': 'Type',
    'profile_unit_cards': "Cartes d'accès",
    'rent_out_button': 'Mettre en location',
    'rent_out_title': 'Louer une unité',
    'rent_term_label': 'Type de location',
    'rent_term_short': 'Court séjour',
    'rent_term_long': 'Longue durée',
    'rent_term_short_hint':
        "Le locataire est seulement enregistré auprès du village. L'eau et l'électricité restent à votre charge.",
    'rent_term_long_hint':
        "Le locataire reçoit un compte. L'eau et l'électricité de ces mois sont facturées au locataire, pas à vous.",
    'rent_start_date': 'Début',
    'rent_end_date': 'Fin',
    'rent_tenant_section': 'Informations sur le locataire',
    'rent_tenant_name': 'Nom complet du locataire',
    'rent_tenant_phone': 'Téléphone du locataire',
    'rent_tenant_phone_hint': "Le locataire se connecte à l'application avec ce numéro.",
    'rent_tenant_id': "N° de pièce d'identité / passeport",
    'rent_id_photo': "Photo de la pièce d'identité / du passeport",
    'rent_id_photo_add': 'Ajouter une photo',
    'rent_id_photo_change': 'Changer la photo',
    'rent_id_photo_camera': 'Prendre une photo',
    'rent_id_photo_gallery': 'Choisir dans la galerie',
    'rent_occupants': "Nombre d'occupants",
    'rent_village_note':
        "Le village est prévenu automatiquement, sans validation nécessaire. Lorsque vous demandez des cartes piscine/plage pour cette unité, la sécurité verra qu'elle est louée.",
    'rent_submit': 'Enregistrer la location',
    'rent_confirm_title': "Transférer l'eau et l'électricité au locataire ?",
    'rent_confirm_body':
        "Du %s au %s, l'eau et l'électricité de cette unité seront facturées au compte du locataire et disparaîtront du vôtre. Les impayés vous reviennent à la fin de la location.",
    'rent_confirm_ok': 'Confirmer',
    'rent_registered': 'Location enregistrée. Le village a été prévenu.',
    'rent_status_active': 'Louée',
    'rent_status_upcoming': 'À venir',
    'rent_status_ended': 'Terminée',
    'rent_rented_to': 'Louée à %s',
    'lease_details_title': 'Détails de la location',
    'lease_tenant': 'Locataire',
    'lease_tenant_phone': 'Téléphone',
    'lease_tenant_id': "Pièce d'identité / passeport",
    'lease_period': 'Période',
    'lease_term': 'Type',
    'lease_occupants': 'Occupants',
    'lease_tenant_balance': 'Reste dû par le locataire',
    'lease_tenant_cleared': 'Le locataire a tout réglé — quitus disponible',
    'lease_end_button': 'Terminer la location',
    'lease_end_confirm_title': 'Terminer cette location ?',
    'lease_end_confirm_body':
        "L'eau et l'électricité reviennent à votre charge dès ce mois. Le locataire peut encore régler ses propres mois et obtenir son quitus.",
    'lease_ended_done': 'Location terminée.',
    'tenant_lease_line': 'Durée du bail : %s – %s',
    'tenant_lease_ended_hint': 'Votre location est terminée. Réglez le solde pour obtenir votre quitus.',

    'rent_adults_section': 'Adultes présents',
    'rent_adults_hint':
        "Chaque adulte reçoit son propre QR code pour l'entrée du village et la piscine. Ajoutez le conjoint du locataire et tout autre adulte, avec une photo de leur pièce d'identité ou passeport.",
    'rent_add_adult': 'Ajouter un adulte',
    'adult_form_title': 'Ajouter un adulte',
    'adult_name': 'Nom complet',
    'adult_id_number': "N° de pièce d'identité / passeport",
    'adult_id_photo': "Photo de la pièce d'identité / du passeport",
    'adult_relation_label': 'Lien avec le locataire',
    'adult_relation_spouse': 'Conjoint(e)',
    'adult_relation_family': 'Membre de la famille',
    'adult_relation_other': 'Autre adulte',
    'rent_docs_section': 'Documents pour la sécurité',
    'rent_docs_hint':
        "Acte de mariage, passeports… Ils sont transmis à la sécurité du village pour que le locataire soit enregistré et son QR code reconnu.",
    'rent_add_document': 'Ajouter un document',
    'doc_kind_marriage': 'Acte de mariage',
    'doc_kind_passport': 'Passeport',
    'doc_kind_other': 'Autre document',
    'doc_label_hint': 'De qui ? (facultatif)',
    'rent_uploads_failed':
        "Location enregistrée, mais %s envoi(s) ont échoué. Ajoutez-les à nouveau depuis les détails de la location.",
    'rent_max_adults': "Cette unité peut accueillir %s adultes, locataire compris.",
    'lease_qr_section': "QR codes — entrée du village et piscine",
    'lease_qr_tenant': 'Locataire',
    'lease_qr_show': 'Afficher le QR',
    'lease_qr_short_hint':
        "Un court séjour n'a pas de compte dans l'application. Montrez ou envoyez ces QR codes à vos invités — ils ouvrent l'entrée du village et la piscine.",
    'lease_valid_until': "Valable jusqu'au %s",
    'lease_adults_section': 'Adultes',
    'lease_add_adult': 'Ajouter un adulte',
    'lease_remove_adult_confirm': 'Retirer %s ? Son QR code cessera de fonctionner.',
    'lease_remove': 'Retirer',
    'lease_docs_section': 'Documents',
    'lease_remove_doc_confirm': 'Retirer ce document ?',
    'lease_extend_button': 'Prolonger',
    'lease_extend_title': "Prolonger la location jusqu'au",
    'lease_extended_done': 'Location prolongée. Les QR codes restent valables.',
    'lease_renew_button': 'Nouvelle période',
    'lease_renew_title': 'Renouveler la location',
    'lease_renew_hint': 'Même locataire, mêmes personnes et mêmes QR codes — seules les dates changent.',
    'lease_renewed_done': 'Nouvelle période de location enregistrée. Les QR codes restent valables.',
    'stay_title': 'Votre séjour',
    'stay_qr_hint': "Présentez ces QR codes à l'entrée du village et à la piscine.",
    'meter_section': 'Relevés des compteurs',
    'meter_hint': "Relevés par l'équipe de maintenance du village au début et à la fin du séjour.",
    'meter_electricity': 'Électricité',
    'meter_water': 'Eau',
    'meter_entry': "À l'entrée",
    'meter_exit': 'À la sortie',
    'meter_pending': 'Pas encore relevé',
    'pm_empty': 'Aucun moyen de paiement enregistré.',
    'pm_intro':
        "Enregistrez votre façon de payer. Les données de carte ne sont jamais conservées dans cette application — elles sont saisies dans le formulaire sécurisé du prestataire de paiement.",
    'pm_add': 'Ajouter un moyen de paiement',
    'pm_default': 'Par défaut',
    'pm_make_default': 'Définir par défaut',
    'pm_remove': 'Supprimer',
    'pm_remove_confirm': 'Supprimer %s ?',
    'pm_card': 'Carte bancaire (Visa, Mastercard, Meeza)',
    'pm_card_soon':
        "Disponible dès le lancement du paiement en ligne. Vous la saisirez dans le formulaire sécurisé du prestataire, jamais ici.",
    'pm_wallet': 'Portefeuille mobile',
    'pm_wallet_hint': 'Vodafone Cash, Orange Cash, Etisalat Cash, WE Pay',
    'pm_wallet_provider': 'Portefeuille',
    'pm_wallet_phone': 'Numéro de téléphone du portefeuille',
    'pm_instapay': 'InstaPay',
    'pm_instapay_hint': 'Payer depuis votre compte bancaire avec votre adresse InstaPay',
    'pm_instapay_address': 'Adresse InstaPay (ex. nom@instapay)',
    'pm_fawry': 'Fawry',
    'pm_fawry_hint': "Payer avec une référence Fawry dans n'importe quel point Fawry",
    'pm_saved': 'Moyen de paiement enregistré.',
    'pm_removed': 'Moyen de paiement supprimé.',
    'pm_full': "Vous avez atteint le nombre maximal de moyens de paiement. Supprimez-en un pour en ajouter un autre.",
  },
  'it': {
    'profile_edit_name': 'Modifica nome',
    'profile_my_units': 'Le mie unità',
    'profile_no_units': 'Nessuna unità è ancora collegata al tuo account.',
    'unit_count_one': '1 unità',
    'unit_count_two': '2 unità',
    'unit_count_many': '%d unità',
    'profile_unit_type': 'Tipo',
    'profile_unit_cards': 'Tessere di accesso',
    'rent_out_button': 'Affitta',
    'rent_out_title': "Affitta un'unità",
    'rent_term_label': 'Tipo di affitto',
    'rent_term_short': 'Soggiorno breve',
    'rent_term_long': 'Lungo periodo',
    'rent_term_short_hint':
        "L'inquilino viene solo registrato presso il villaggio. Acqua ed elettricità restano a tuo carico.",
    'rent_term_long_hint':
        "L'inquilino riceve un account. Acqua ed elettricità di questi mesi vengono addebitate all'inquilino, non a te.",
    'rent_start_date': 'Inizio',
    'rent_end_date': 'Fine',
    'rent_tenant_section': "Dati dell'inquilino",
    'rent_tenant_name': "Nome completo dell'inquilino",
    'rent_tenant_phone': "Telefono dell'inquilino",
    'rent_tenant_phone_hint': "L'inquilino accede all'app con questo numero.",
    'rent_tenant_id': "N. documento d'identità / passaporto",
    'rent_id_photo': 'Foto del documento / passaporto',
    'rent_id_photo_add': 'Aggiungi foto',
    'rent_id_photo_change': 'Cambia foto',
    'rent_id_photo_camera': 'Scatta una foto',
    'rent_id_photo_gallery': 'Scegli dalla galleria',
    'rent_occupants': 'Numero di occupanti',
    'rent_village_note':
        'Il villaggio viene avvisato automaticamente, senza bisogno di approvazione. Quando richiedi le tessere piscina/spiaggia per questa unità, la sicurezza vedrà che è affittata.',
    'rent_submit': "Registra l'affitto",
    'rent_confirm_title': "Trasferire acqua ed elettricità all'inquilino?",
    'rent_confirm_body':
        "Dal %s al %s acqua ed elettricità di questa unità saranno addebitate all'inquilino e spariranno dal tuo conto. Gli importi non pagati tornano a te al termine dell'affitto.",
    'rent_confirm_ok': 'Conferma',
    'rent_registered': 'Affitto registrato. Il villaggio è stato avvisato.',
    'rent_status_active': 'Affittata',
    'rent_status_upcoming': 'In arrivo',
    'rent_status_ended': 'Terminato',
    'rent_rented_to': 'Affittata a %s',
    'lease_details_title': "Dettagli dell'affitto",
    'lease_tenant': 'Inquilino',
    'lease_tenant_phone': 'Telefono',
    'lease_tenant_id': 'Documento / passaporto',
    'lease_period': 'Periodo',
    'lease_term': 'Tipo',
    'lease_occupants': 'Occupanti',
    'lease_tenant_balance': "Ancora dovuto dall'inquilino",
    'lease_tenant_cleared': "L'inquilino ha pagato tutto — attestato di saldo disponibile",
    'lease_end_button': "Termina l'affitto",
    'lease_end_confirm_title': 'Terminare questo affitto?',
    'lease_end_confirm_body':
        "Acqua ed elettricità tornano a tuo carico da questo mese. L'inquilino può ancora saldare i propri mesi e ottenere l'attestato di saldo.",
    'lease_ended_done': 'Affitto terminato.',
    'tenant_lease_line': 'Durata del contratto: %s – %s',
    'tenant_lease_ended_hint': "Il tuo affitto è terminato. Salda quanto resta per ottenere l'attestato di saldo.",

    'rent_adults_section': 'Adulti presenti',
    'rent_adults_hint':
        "Ogni adulto riceve il proprio QR per l'ingresso del villaggio e la piscina. Aggiungi il coniuge dell'inquilino e ogni altro adulto, con la foto del documento d'identità o del passaporto.",
    'rent_add_adult': 'Aggiungi un adulto',
    'adult_form_title': 'Aggiungi un adulto',
    'adult_name': 'Nome completo',
    'adult_id_number': "N. documento d'identità / passaporto",
    'adult_id_photo': 'Foto del documento / passaporto',
    'adult_relation_label': "Rapporto con l'inquilino",
    'adult_relation_spouse': 'Coniuge',
    'adult_relation_family': 'Familiare',
    'adult_relation_other': 'Altro adulto',
    'rent_docs_section': 'Documenti per la sicurezza',
    'rent_docs_hint':
        "Certificato di matrimonio, passaporti… Vengono inviati alla sicurezza del villaggio affinché l'inquilino sia registrato e il suo QR riconosciuto.",
    'rent_add_document': 'Aggiungi un documento',
    'doc_kind_marriage': 'Certificato di matrimonio',
    'doc_kind_passport': 'Passaporto',
    'doc_kind_other': 'Altro documento',
    'doc_label_hint': 'Di chi? (facoltativo)',
    'rent_uploads_failed':
        "Affitto registrato, ma %s caricamento/i non riuscito/i. Aggiungili di nuovo dai dettagli dell'affitto.",
    'rent_max_adults': "Questa unità ha posto per %s adulti, inquilino compreso.",
    'lease_qr_section': 'Codici QR — ingresso del villaggio e piscina',
    'lease_qr_tenant': 'Inquilino',
    'lease_qr_show': 'Mostra il QR',
    'lease_qr_short_hint':
        "Un soggiorno breve non ha un account nell'app. Mostra o invia questi codici QR ai tuoi ospiti: aprono l'ingresso del villaggio e la piscina.",
    'lease_valid_until': 'Valido fino al %s',
    'lease_adults_section': 'Adulti',
    'lease_add_adult': 'Aggiungi un adulto',
    'lease_remove_adult_confirm': 'Rimuovere %s? Il suo QR smetterà di funzionare.',
    'lease_remove': 'Rimuovi',
    'lease_docs_section': 'Documenti',
    'lease_remove_doc_confirm': 'Rimuovere questo documento?',
    'lease_extend_button': 'Prolunga',
    'lease_extend_title': "Prolunga l'affitto fino al",
    'lease_extended_done': 'Affitto prolungato. I codici QR restano validi.',
    'lease_renew_button': 'Nuovo periodo',
    'lease_renew_title': "Rinnova l'affitto",
    'lease_renew_hint': 'Stesso inquilino, stesse persone e stessi codici QR: cambiano solo le date.',
    'lease_renewed_done': 'Nuovo periodo di affitto registrato. I codici QR restano validi.',
    'stay_title': 'Il tuo soggiorno',
    'stay_qr_hint': "Mostra questi codici QR all'ingresso del villaggio e in piscina.",
    'meter_section': 'Letture dei contatori',
    'meter_hint': "Rilevate dal team di manutenzione del villaggio all'inizio e alla fine del soggiorno.",
    'meter_electricity': 'Elettricità',
    'meter_water': 'Acqua',
    'meter_entry': "All'ingresso",
    'meter_exit': "All'uscita",
    'meter_pending': 'Non ancora letto',
    'pm_empty': 'Nessun metodo di pagamento salvato.',
    'pm_intro':
        "Salva come preferisci pagare. I dati della carta non vengono mai conservati in questa app: le carte si inseriscono nel modulo sicuro del fornitore di pagamenti.",
    'pm_add': 'Aggiungi metodo di pagamento',
    'pm_default': 'Predefinito',
    'pm_make_default': 'Imposta come predefinito',
    'pm_remove': 'Rimuovi',
    'pm_remove_confirm': 'Rimuovere %s?',
    'pm_card': 'Carta bancaria (Visa, Mastercard, Meeza)',
    'pm_card_soon':
        "Disponibile quando il pagamento online sarà attivo. La inserirai nel modulo sicuro del fornitore, mai qui.",
    'pm_wallet': 'Portafoglio mobile',
    'pm_wallet_hint': 'Vodafone Cash, Orange Cash, Etisalat Cash, WE Pay',
    'pm_wallet_provider': 'Portafoglio',
    'pm_wallet_phone': 'Numero di telefono del portafoglio',
    'pm_instapay': 'InstaPay',
    'pm_instapay_hint': 'Paga dal tuo conto bancario con il tuo indirizzo InstaPay',
    'pm_instapay_address': 'Indirizzo InstaPay (es. nome@instapay)',
    'pm_fawry': 'Fawry',
    'pm_fawry_hint': 'Paga con un riferimento Fawry in qualsiasi punto Fawry',
    'pm_saved': 'Metodo di pagamento salvato.',
    'pm_removed': 'Metodo di pagamento rimosso.',
    'pm_full': 'Hai raggiunto il numero massimo di metodi di pagamento. Rimuovine uno per aggiungerne un altro.',
  },
  'ru': {
    'profile_edit_name': 'Изменить имя',
    'profile_my_units': 'Мои объекты',
    'profile_no_units': 'К вашему аккаунту пока не привязаны объекты.',
    'unit_count_one': '1 объект',
    'unit_count_two': '2 объекта',
    'unit_count_many': 'Объектов: %d',
    'profile_unit_type': 'Тип',
    'profile_unit_cards': 'Карты доступа',
    'rent_out_button': 'Сдать в аренду',
    'rent_out_title': 'Сдать объект в аренду',
    'rent_term_label': 'Тип аренды',
    'rent_term_short': 'Краткосрочное проживание',
    'rent_term_long': 'Долгосрочная аренда',
    'rent_term_short_hint':
        'Арендатор только регистрируется в посёлке. Вода и электричество остаются на вашем счёте.',
    'rent_term_long_hint':
        'Арендатор получает аккаунт. Вода и электричество за эти месяцы начисляются арендатору, а не вам.',
    'rent_start_date': 'Начало',
    'rent_end_date': 'Окончание',
    'rent_tenant_section': 'Данные арендатора',
    'rent_tenant_name': 'ФИО арендатора',
    'rent_tenant_phone': 'Телефон арендатора',
    'rent_tenant_phone_hint': 'Арендатор входит в приложение по этому номеру.',
    'rent_tenant_id': 'Номер удостоверения / паспорта',
    'rent_id_photo': 'Фото удостоверения / паспорта',
    'rent_id_photo_add': 'Добавить фото',
    'rent_id_photo_change': 'Изменить фото',
    'rent_id_photo_camera': 'Сделать фото',
    'rent_id_photo_gallery': 'Выбрать из галереи',
    'rent_occupants': 'Количество проживающих',
    'rent_village_note':
        'Посёлок уведомляется автоматически, одобрение не требуется. Когда вы запросите карты для бассейна/пляжа для этого объекта, охрана увидит, что он сдан.',
    'rent_submit': 'Зарегистрировать аренду',
    'rent_confirm_title': 'Перевести воду и электричество на арендатора?',
    'rent_confirm_body':
        'С %s по %s вода и электричество по этому объекту будут начисляться на счёт арендатора и исчезнут с вашего. Неоплаченное вернётся к вам после окончания аренды.',
    'rent_confirm_ok': 'Подтвердить',
    'rent_registered': 'Аренда зарегистрирована. Посёлок уведомлён.',
    'rent_status_active': 'Сдан',
    'rent_status_upcoming': 'Скоро',
    'rent_status_ended': 'Завершена',
    'rent_rented_to': 'Сдан: %s',
    'lease_details_title': 'Детали аренды',
    'lease_tenant': 'Арендатор',
    'lease_tenant_phone': 'Телефон',
    'lease_tenant_id': 'Удостоверение / паспорт',
    'lease_period': 'Период',
    'lease_term': 'Тип',
    'lease_occupants': 'Проживающих',
    'lease_tenant_balance': 'Долг арендатора',
    'lease_tenant_cleared': 'Арендатор всё оплатил — справка об отсутствии задолженности доступна',
    'lease_end_button': 'Завершить аренду',
    'lease_end_confirm_title': 'Завершить эту аренду?',
    'lease_end_confirm_body':
        'Вода и электричество вернутся на ваш счёт с этого месяца. Арендатор по-прежнему может оплатить свои месяцы и получить справку об отсутствии задолженности.',
    'lease_ended_done': 'Аренда завершена.',
    'tenant_lease_line': 'Срок аренды: %s – %s',
    'tenant_lease_ended_hint':
        'Ваша аренда закончилась. Оплатите остаток, чтобы получить справку об отсутствии задолженности.',

    'rent_adults_section': 'Проживающие взрослые',
    'rent_adults_hint':
        'Каждый взрослый получает свой QR-код для въезда в посёлок и бассейна. Добавьте супруга(у) арендатора и других взрослых — с фото удостоверения или паспорта.',
    'rent_add_adult': 'Добавить взрослого',
    'adult_form_title': 'Добавить взрослого',
    'adult_name': 'ФИО',
    'adult_id_number': 'Номер удостоверения / паспорта',
    'adult_id_photo': 'Фото удостоверения / паспорта',
    'adult_relation_label': 'Кем приходится арендатору',
    'adult_relation_spouse': 'Супруг(а)',
    'adult_relation_family': 'Член семьи',
    'adult_relation_other': 'Другой взрослый',
    'rent_docs_section': 'Документы для охраны',
    'rent_docs_hint':
        'Свидетельство о браке, паспорта… Они передаются охране посёлка, чтобы арендатор был зарегистрирован, а его QR-код распознавался.',
    'rent_add_document': 'Добавить документ',
    'doc_kind_marriage': 'Свидетельство о браке',
    'doc_kind_passport': 'Паспорт',
    'doc_kind_other': 'Другой документ',
    'doc_label_hint': 'Чей документ? (необязательно)',
    'rent_uploads_failed':
        'Аренда зарегистрирована, но не удалось загрузить файлов: %s. Добавьте их снова в деталях аренды.',
    'rent_max_adults': 'В этом объекте могут проживать %s взрослых, включая арендатора.',
    'lease_qr_section': 'QR-коды — въезд в посёлок и бассейн',
    'lease_qr_tenant': 'Арендатор',
    'lease_qr_show': 'Показать QR',
    'lease_qr_short_hint':
        'У краткосрочного проживания нет аккаунта в приложении. Покажите или отправьте эти QR-коды гостям — они открывают въезд в посёлок и бассейн.',
    'lease_valid_until': 'Действует до %s',
    'lease_adults_section': 'Взрослые',
    'lease_add_adult': 'Добавить взрослого',
    'lease_remove_adult_confirm': 'Удалить %s? Его QR-код перестанет работать.',
    'lease_remove': 'Удалить',
    'lease_docs_section': 'Документы',
    'lease_remove_doc_confirm': 'Удалить этот документ?',
    'lease_extend_button': 'Продлить',
    'lease_extend_title': 'Продлить аренду до',
    'lease_extended_done': 'Аренда продлена. QR-коды остаются действительными.',
    'lease_renew_button': 'Новый период',
    'lease_renew_title': 'Возобновить аренду',
    'lease_renew_hint': 'Тот же арендатор, те же люди и те же QR-коды — меняются только даты.',
    'lease_renewed_done': 'Новый период аренды зарегистрирован. QR-коды остаются действительными.',
    'stay_title': 'Ваше пребывание',
    'stay_qr_hint': 'Покажите эти QR-коды при въезде в посёлок и у бассейна.',
    'meter_section': 'Показания счётчиков',
    'meter_hint': 'Снимаются службой эксплуатации посёлка при заезде и при выезде.',
    'meter_electricity': 'Электричество',
    'meter_water': 'Вода',
    'meter_entry': 'При заезде',
    'meter_exit': 'При выезде',
    'meter_pending': 'Ещё не сняты',
    'pm_empty': 'Сохранённых способов оплаты пока нет.',
    'pm_intro':
        'Сохраните удобный для вас способ оплаты. Данные карты в этом приложении не хранятся — карты вводятся в защищённой форме платёжного провайдера.',
    'pm_add': 'Добавить способ оплаты',
    'pm_default': 'По умолчанию',
    'pm_make_default': 'Сделать основным',
    'pm_remove': 'Удалить',
    'pm_remove_confirm': 'Удалить %s?',
    'pm_card': 'Банковская карта (Visa, Mastercard, Meeza)',
    'pm_card_soon':
        'Станет доступна, когда заработает онлайн-оплата. Вы введёте её в защищённой форме провайдера, но не здесь.',
    'pm_wallet': 'Мобильный кошелёк',
    'pm_wallet_hint': 'Vodafone Cash, Orange Cash, Etisalat Cash, WE Pay',
    'pm_wallet_provider': 'Кошелёк',
    'pm_wallet_phone': 'Номер телефона кошелька',
    'pm_instapay': 'InstaPay',
    'pm_instapay_hint': 'Оплата с банковского счёта по вашему адресу InstaPay',
    'pm_instapay_address': 'Адрес InstaPay (например, name@instapay)',
    'pm_fawry': 'Fawry',
    'pm_fawry_hint': 'Оплата по референсу Fawry в любом пункте Fawry',
    'pm_saved': 'Способ оплаты сохранён.',
    'pm_removed': 'Способ оплаты удалён.',
    'pm_full': 'Достигнуто максимальное число способов оплаты. Удалите один, чтобы добавить другой.',
  },
};
