import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Unit Charges & Fees',
      'tickets_title': 'Support & Maintenance',
      'passes_title': 'Gate & Beach Passes',
      'pay_now': 'Pay Selected Charges',
      'create_ticket': 'New Support Request',
      'create_pass': 'New Visitor Pass',
      'no_charges': 'No charges found',
      'no_tickets': 'No support tickets found',
      'no_passes': 'No gate passes found',
      'status_published': 'Published',
      'status_paid': 'Paid',
      'status_unpaid': 'Unpaid',
      'unit': 'Unit',
      'amount': 'Amount',
      'remaining': 'Remaining',
      'details': 'Details',
      'qr_code': 'Show Entry QR Code',
      'login_title': 'Welcome to OwnerConnect',
      'login_subtitle': 'Select your country and enter your phone number to continue',
      'phone_hint': 'Phone number',
      'continue_button': 'Continue',
      'invalid_phone': 'Please enter a valid phone number',
      'dev_bypass_button': 'Developer Test Sign-In',
      'otp_title': 'Verification Code',
      'otp_subtitle': 'Enter the 6-digit code sent to',
      'verify_button': 'Verify',
      'resend_code': 'Resend Code',
      'resend_in': 'Resend code in',
      'pending_resort_title': 'Account Not Linked Yet',
      'pending_resort_message':
          'Your account exists but isn\'t linked to a resort/village yet. Please contact your resort administration.',
      'logout': 'Logout',
      'or_divider': 'or',
      'continue_with_google': 'Continue with Google',
      'continue_with_email': 'Continue with Email',
      'email_hint': 'Email',
      'password_hint': 'Password',
      'sign_in_button': 'Sign In',
      'register_button': 'Create Account',
      'toggle_to_register': 'Don\'t have an account? Create one',
      'toggle_to_sign_in': 'Already have an account? Sign in',
      'link_account_title': 'Link Your Account',
      'link_account_subtitle':
          'Enter the phone number on file with your resort and the activation code given to you by staff.',
      'activation_code_hint': 'Activation code',
      'role_owner': 'Owner',
      'role_tenant': 'Tenant',
      'checkout_title': 'Checkout',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'order_id': 'Order ID',
      'payment_processed_success': 'Your payment has been processed successfully.',
      'payment_options_title': 'Payment Options',
      'pay_online_option': 'Pay Online',
      'pay_online_subtitle': 'Pay now with a card via the payment gateway.',
      'defer_option': 'Defer Payment',
      'defer_subtitle': 'Push the due date back by up to 3 days.',
      'defer_multi_charge_note': 'Deferral and payment plans are only available one charge at a time — select a single charge to use them.',
      'deferred_to_label': 'Deferred to',
      'payment_plan_option': 'Request a Payment Plan',
      'payment_plan_subtitle': 'Propose installments for a large amount — needs accountant approval.',
      'payment_plan_pending': 'Your payment plan request was submitted and is pending accountant approval.',
      'pay_at_office_option': 'Pay Cash at the Accounts Office',
      'pay_at_office_subtitle': 'Pick a date and we will notify the accounts office you are coming.',
      'pay_at_office_subject': 'Cash payment at accounts office',
      'pay_at_office_description': 'Owner will pay cash at the accounts office on',
      'pay_at_office_confirmed': "You're all set — the accounts office will be expecting you on your chosen date. It will be our pleasure to welcome you.",
      'pick_date': 'Pick a date',
      'add_installment': 'Add installment',
      'submit_request': 'Submit Request',
      'cancel': 'Cancel',
      'legend_issued': 'Debt issued',
      'legend_today': 'Today',
      'legend_selected': 'Selected',
      'profile_title': 'Profile',
      'settings_title': 'Settings',
      'payment_methods_title': 'Payment Methods',
      'contact_us_title': 'Contact Us',
      'about_title': 'About',
      'language_title': 'Language',
      'role_label': 'Role',
      'village_label': 'Village',
      'fullname_hint': 'Full name',
      'save_button': 'Save',
      'profile_saved': 'Profile updated.',
      'payment_methods_coming_soon': 'Online payment setup is in progress. You will be able to add a payment method here soon.',
      'contact_us_sent': 'Your message was sent — we will get back to you soon.',
      'contact_us_no_unit': 'No unit linked to your account yet.',
      'contact_us_subject_hint': 'Subject',
      'contact_us_message_hint': 'Your message',
      'about_version': 'Version 1.0.0',
      'about_description': 'OwnerConnect helps you manage your unit, charges, and requests at your resort — all in one place.',
    },
    'ar': {
      'app_title': 'أونر كونكت',
      'charges_title': 'مستحقات وفواتير الوحدة',
      'tickets_title': 'الدعم الفني والصيانة',
      'passes_title': 'تصاريح البوابة والشاطئ',
      'pay_now': 'سداد المستحقات المحددة',
      'create_ticket': 'طلب صيانة جديد',
      'create_pass': 'تصريح دخول جديد',
      'no_charges': 'لا توجد مستحقات حالياً',
      'no_tickets': 'لا توجد تذاكر دعم فني',
      'no_passes': 'لا توجد تصاريح دخول',
      'status_published': 'معتمدة',
      'status_paid': 'مسددة',
      'status_unpaid': 'غير مسددة',
      'unit': 'الوحدة',
      'amount': 'المبلغ',
      'remaining': 'المتبقي',
      'details': 'التفاصيل',
      'qr_code': 'عرض رمز QR للدخول',
      'login_title': 'مرحباً بك في أونر كونكت',
      'login_subtitle': 'اختر دولتك وادخل رقم موبايلك للمتابعة',
      'phone_hint': 'رقم الموبايل',
      'continue_button': 'متابعة',
      'invalid_phone': 'من فضلك ادخل رقم موبايل صحيح',
      'dev_bypass_button': 'دخول تجريبي للمطورين',
      'otp_title': 'كود التفعيل',
      'otp_subtitle': 'ادخل الكود المكوّن من 6 أرقام المرسل إلى',
      'verify_button': 'تأكيد',
      'resend_code': 'إعادة إرسال الكود',
      'resend_in': 'إعادة الإرسال خلال',
      'pending_resort_title': 'الحساب لسه مش مربوط بقرية',
      'pending_resort_message':
          'حسابك موجود بس لسه محدش ربطه بقرية أو وحدة. من فضلك تواصل مع إدارة القرية.',
      'logout': 'تسجيل الخروج',
      'or_divider': 'أو',
      'continue_with_google': 'الدخول بحساب جوجل',
      'continue_with_email': 'الدخول بالإيميل',
      'email_hint': 'الإيميل',
      'password_hint': 'كلمة المرور',
      'sign_in_button': 'تسجيل الدخول',
      'register_button': 'إنشاء حساب',
      'toggle_to_register': 'معندكش حساب؟ اعمل واحد',
      'toggle_to_sign_in': 'عندك حساب أصلاً؟ سجل دخول',
      'link_account_title': 'اربط حسابك',
      'link_account_subtitle':
          'ادخل رقم موبايلك المسجل عند القرية وكود التفعيل اللي أداك الموظف.',
      'activation_code_hint': 'كود التفعيل',
      'role_owner': 'مالك',
      'role_tenant': 'مستأجر',
      'checkout_title': 'الدفع',
      'payment_successful': 'تم الدفع بنجاح',
      'payment_failed': 'فشل الدفع',
      'order_id': 'رقم الطلب',
      'payment_processed_success': 'تم تنفيذ عملية الدفع بنجاح.',
      'payment_options_title': 'خيارات السداد',
      'pay_online_option': 'الدفع أونلاين',
      'pay_online_subtitle': 'ادفع الآن بالبطاقة عن طريق بوابة الدفع.',
      'defer_option': 'تأجيل السداد',
      'defer_subtitle': 'أجل موعد السداد لحد 3 أيام.',
      'defer_multi_charge_note': 'التأجيل وخطة السداد متاحين لفاتورة واحدة بس في المرة — اختار فاتورة واحدة عشان تستخدمهم.',
      'deferred_to_label': 'تم تأجيل الدفع ليوم',
      'payment_plan_option': 'طلب خطة سداد',
      'payment_plan_subtitle': 'اقترح دفعات لمبلغ كبير — محتاج موافقة المحاسب.',
      'payment_plan_pending': 'تم إرسال طلب خطة السداد وهو في انتظار موافقة المحاسب.',
      'pay_at_office_option': 'الدفع كاش في مكتب الحسابات',
      'pay_at_office_subtitle': 'اختار يوم وهنبلغ مكتب الحسابات إنك جاي.',
      'pay_at_office_subject': 'سداد كاش في مكتب الحسابات',
      'pay_at_office_description': 'المالك هيدفع كاش في مكتب الحسابات يوم',
      'pay_at_office_confirmed': 'تمام كده، مكتب الحسابات هيكون في انتظارك في الميعاد اللي حددته. تشرفنا هنكون في استقبالك.',
      'pick_date': 'اختار تاريخ',
      'add_installment': 'إضافة دفعة',
      'submit_request': 'إرسال الطلب',
      'cancel': 'إلغاء',
      'legend_issued': 'تاريخ صدور المديونية',
      'legend_today': 'اليوم',
      'legend_selected': 'المحدد',
      'profile_title': 'البروفايل',
      'settings_title': 'الإعدادات',
      'payment_methods_title': 'وسائل الدفع',
      'contact_us_title': 'تواصل معنا',
      'about_title': 'عن التطبيق',
      'language_title': 'اللغة',
      'role_label': 'الصفة',
      'village_label': 'القرية',
      'fullname_hint': 'الاسم بالكامل',
      'save_button': 'حفظ',
      'profile_saved': 'تم تحديث البروفايل.',
      'payment_methods_coming_soon': 'جاري تجهيز الدفع الإلكتروني. هتقدر تضيف وسيلة دفع من هنا قريبًا.',
      'contact_us_sent': 'تم إرسال رسالتك — هنتواصل معاك قريب.',
      'contact_us_no_unit': 'مفيش وحدة مرتبطة بحسابك لسه.',
      'contact_us_subject_hint': 'الموضوع',
      'contact_us_message_hint': 'رسالتك',
      'about_version': 'الإصدار 1.0.0',
      'about_description': 'أونر كونكت بيساعدك تدير وحدتك وفواتيرك وطلباتك في القرية — كل حاجة في مكان واحد.',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
