import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Unit Charges & Fees',
      'tickets_title': 'Support & Maintenance',
      'passes_title': 'Gate & Beach Passes',
      'pay_now': 'Pay Selected Charges',
      'create_ticket': 'New Support Request',
      'select_issue_type': "What's the issue?",
      'category_electrician': 'Electrician',
      'category_plumber': 'Plumber',
      'category_carpenter': 'Carpenter',
      'category_satellite': 'Satellite Technician',
      'category_gardening': 'Gardening & Agriculture',
      'category_pest_control': 'Pest Control',
      'issue_details_hint': 'Add more details (optional)',
      'ticket_submitted': 'Your request was submitted — our team will contact you soon.',
      'create_pass': 'New Visitor Pass',
      'no_charges': 'No charges found',
      'no_tickets': 'No support tickets found',
      'no_passes': 'No gate passes found',
      'status_published': 'Published',
      'status_paid': 'Paid',
      'status_unpaid': 'Unpaid',
      'unit': 'Unit',
      'amount': 'Amount',
      'remaining': 'Remaining',
      'details': 'Details',
      'qr_code': 'Show Entry QR Code',
      'pass_code_label': 'Code',
      'splash_tagline': 'Smart resort living, connected',
      'splash_checking': 'Checking your session…',
      'login_title': 'Welcome to OwnerConnect',
      'login_subtitle': 'Select your country and enter your phone number to continue',
      'phone_hint': 'Phone number',
      'continue_button': 'Continue',
      'invalid_phone': 'Please enter a valid phone number',
      'dev_bypass_button': 'Developer Test Sign-In',
      'otp_title': 'Verification Code',
      'otp_subtitle': 'Enter the 6-digit code sent to',
      'verify_button': 'Verify',
      'resend_code': 'Resend Code',
      'resend_in': 'Resend code in',
      'pending_resort_title': 'Account Not Linked Yet',
      'pending_resort_message':
          'Your account exists but isn\'t linked to a resort/village yet. Please contact your resort administration.',
      'logout': 'Logout',
      'or_divider': 'or',
      'or_continue_another_way': 'or continue another way',
      'continue_with_google': 'Continue with Google',
      'continue_with_email': 'Continue with Email',
      'email_hint': 'Email',
      'password_hint': 'Password',
      'sign_in_button': 'Sign In',
      'register_button': 'Create Account',
      'toggle_to_register': 'Don\'t have an account? Create one',
      'toggle_to_sign_in': 'Already have an account? Sign in',
      'link_account_title': 'Link Your Account',
      'link_account_subtitle':
          'Enter the phone number on file with your resort and the activation code given to you by staff.',
      'activation_code_hint': 'Activation code',
      'role_owner': 'Owner',
      'role_tenant': 'Tenant',
      'checkout_title': 'Checkout',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'order_id': 'Order ID',
      'payment_processed_success': 'Your payment has been processed successfully.',
      'payment_options_title': 'Payment Options',
      'pay_online_option': 'Pay Online',
      'pay_online_subtitle': 'Pay now with a card via the payment gateway.',
      'defer_option': 'Defer Payment',
      'defer_subtitle': 'Push the due date back by up to 3 days.',
      'defer_multi_charge_note': 'Deferral and payment plans are only available one charge at a time — select a single charge to use them.',
      'deferred_to_label': 'Deferred to',
      'payment_plan_option': 'Request a Payment Plan',
      'payment_plan_subtitle': 'Propose installments for a large amount — needs accountant approval.',
      'payment_plan_pending': 'Your payment plan request was submitted and is pending accountant approval.',
      'pay_at_office_option': 'Pay Cash at the Accounts Office',
      'pay_at_office_subtitle': 'Pick a date and we will notify the accounts office you are coming.',
      'pay_at_office_subject': 'Cash payment at accounts office',
      'pay_at_office_description': 'Owner will pay cash at the accounts office on',
      'pay_at_office_confirmed': "You're all set — the accounts office will be expecting you on your chosen date. It will be our pleasure to welcome you.",
      'per_unit_selection_note': 'Your selection covers more than one unit — each unit will get its own separate receipt.',
      'pay_partial_toggle': 'Pay a partial amount',
      'pay_partial_amount_label': 'Amount to pay now',
      'remaining_due_date_label': 'Remaining balance due by',
      'pay_partial_cap_note': 'Up to 5 days from today. For longer, contact the accounts office.',
      'pay_partial_invalid_amount': 'Enter an amount greater than 0 and no more than the total.',
      'pay_partial_date_required': 'Choose when you will pay the rest.',
      'pick_date': 'Pick a date',
      'add_installment': 'Add installment',
      'submit_request': 'Submit Request',
      'cancel': 'Cancel',
      'close_button': 'Close',
      'legend_issued': 'Debt issued',
      'legend_today': 'Today',
      'legend_selected': 'Selected',
      'profile_title': 'Profile',
      'settings_title': 'Settings',
      'payment_methods_title': 'Payment Methods',
      'contact_us_title': 'Contact Us',
      'about_title': 'About',
      'language_title': 'Language',
      'role_label': 'Role',
      'village_label': 'Village',
      'fullname_hint': 'Full name',
      'save_button': 'Save',
      'profile_saved': 'Profile updated.',
      'payment_methods_coming_soon': 'Online payment setup is in progress. You will be able to add a payment method here soon.',
      'contact_us_sent': 'Your message was sent — we will get back to you soon.',
      'contact_us_no_unit': 'No unit linked to your account yet.',
      'load_unit_error': "Couldn't load your unit. Check your connection and try again.",
      'retry_button': "Retry",
      'contact_us_subject_hint': 'Subject',
      'contact_us_message_hint': 'Your message',
      'about_version': 'Version 1.0.0',
      'about_description': 'OwnerConnect helps you manage your unit, charges, and requests at your resort — all in one place.',
      'notifications_title': 'Notifications',
      'mark_all_read': 'Mark all read',
      'no_notifications_yet': 'No notifications yet',
      'payment_history_title': 'Payment History',
      'download_receipt': 'Download Receipt',
      'no_payments_yet': 'No payments found',
      'receipt_no_label': 'Receipt No.',
      'filter_by_month': 'Filter by month',
      'clear_filter': 'Clear filter',
      'combined_total': 'Combined Total Due',
      'per_unit_breakdown': 'Breakdown by unit',
      'clearance_title': 'Clearance Statement',
      'generate_clearance': 'Issue Clearance Statement',
      'as_of_date': 'As of date',
      'clearance_clear_status': 'No Outstanding Dues',
      'clearance_outstanding_status': 'Outstanding Balance',
      'clearance_history': 'Previous Statements',
      'no_clearance_yet': 'No clearance statements yet',
      'select_unit': 'Select unit',
      'select_resort_title': 'Select Your Resort',
      'select_resort_subtitle': 'Choose the resort your unit belongs to',
      'search_resort_hint': 'Search resorts',
      'no_resorts_found': 'No resorts found',
      'welcome_to_resort': 'Welcome to',
      'welcome_resort_subtitle': "Glad to have you with us",
      'retry': 'Retry',
    },
    'ar': {
      'app_title': 'أونر كونكت',
      'charges_title': 'مستحقات وفواتير الوحدة',
      'tickets_title': 'الدعم الفني والصيانة',
      'passes_title': 'تصاريح البوابة والشاطئ',
      'pay_now': 'سداد المستحقات المحددة',
      'create_ticket': 'طلب صيانة جديد',
      'select_issue_type': 'احتاج مساعدة في إيه؟',
      'category_electrician': 'كهربائي',
      'category_plumber': 'سباك',
      'category_carpenter': 'نجار',
      'category_satellite': 'فني ستالايت',
      'category_gardening': 'فني زراعة',
      'category_pest_control': 'مكافحة حشرات',
      'issue_details_hint': 'تفاصيل إضافية (اختياري)',
      'ticket_submitted': 'تم إرسال طلبك — هيتواصل معاك فريقنا قريب.',
      'create_pass': 'تصريح دخول جديد',
      'no_charges': 'لا توجد مستحقات حالياً',
      'no_tickets': 'لا توجد تذاكر دعم فني',
      'no_passes': 'لا توجد تصاريح دخول',
      'status_published': 'معتمدة',
      'status_paid': 'مسددة',
      'status_unpaid': 'غير مسددة',
      'unit': 'الوحدة',
      'amount': 'المبلغ',
      'remaining': 'المتبقي',
      'details': 'التفاصيل',
      'qr_code': 'عرض رمز QR للدخول',
      'pass_code_label': 'الكود',
      'splash_tagline': 'منظومة القرى الساحلية الذكية',
      'splash_checking': 'جاري التحقق من حسابك…',
      'login_title': 'مرحباً بك في أونر كونكت',
      'login_subtitle': 'اختر دولتك وادخل رقم موبايلك للمتابعة',
      'phone_hint': 'رقم الموبايل',
      'continue_button': 'متابعة',
      'invalid_phone': 'من فضلك ادخل رقم موبايل صحيح',
      'dev_bypass_button': 'دخول تجريبي للمطورين',
      'otp_title': 'كود التفعيل',
      'otp_subtitle': 'ادخل الكود المكوّن من 6 أرقام المرسل إلى',
      'verify_button': 'تأكيد',
      'resend_code': 'إعادة إرسال الكود',
      'resend_in': 'إعادة الإرسال خلال',
      'pending_resort_title': 'الحساب لسه مش مربوط بقرية',
      'pending_resort_message':
          'حسابك موجود بس لسه محدش ربطه بقرية أو وحدة. من فضلك تواصل مع إدارة القرية.',
      'logout': 'تسجيل الخروج',
      'or_divider': 'أو',
      'or_continue_another_way': 'أو تابع بطريقة تانية',
      'continue_with_google': 'الدخول بحساب جوجل',
      'continue_with_email': 'الدخول بالإيميل',
      'email_hint': 'الإيميل',
      'password_hint': 'كلمة المرور',
      'sign_in_button': 'تسجيل الدخول',
      'register_button': 'إنشاء حساب',
      'toggle_to_register': 'معندكش حساب؟ اعمل واحد',
      'toggle_to_sign_in': 'عندك حساب أصلاً؟ سجل دخول',
      'link_account_title': 'اربط حسابك',
      'link_account_subtitle':
          'ادخل رقم موبايلك المسجل عند القرية وكود التفعيل اللي أداك الموظف.',
      'activation_code_hint': 'كود التفعيل',
      'role_owner': 'مالك',
      'role_tenant': 'مستأجر',
      'checkout_title': 'الدفع',
      'payment_successful': 'تم الدفع بنجاح',
      'payment_failed': 'فشل الدفع',
      'order_id': 'رقم الطلب',
      'payment_processed_success': 'تم تنفيذ عملية الدفع بنجاح.',
      'payment_options_title': 'خيارات السداد',
      'pay_online_option': 'الدفع أونلاين',
      'pay_online_subtitle': 'ادفع الآن بالبطاقة عن طريق بوابة الدفع.',
      'defer_option': 'تأجيل السداد',
      'defer_subtitle': 'أجل موعد السداد لحد 3 أيام.',
      'defer_multi_charge_note': 'التأجيل وخطة السداد متاحين لفاتورة واحدة بس في المرة — اختار فاتورة واحدة عشان تستخدمهم.',
      'deferred_to_label': 'تم تأجيل الدفع ليوم',
      'payment_plan_option': 'طلب خطة سداد',
      'payment_plan_subtitle': 'اقترح دفعات لمبلغ كبير — محتاج موافقة المحاسب.',
      'payment_plan_pending': 'تم إرسال طلب خطة السداد وهو في انتظار موافقة المحاسب.',
      'pay_at_office_option': 'الدفع كاش في مكتب الحسابات',
      'pay_at_office_subtitle': 'اختار يوم وهنبلغ مكتب الحسابات إنك جاي.',
      'pay_at_office_subject': 'سداد كاش في مكتب الحسابات',
      'pay_at_office_description': 'المالك هيدفع كاش في مكتب الحسابات يوم',
      'pay_at_office_confirmed': 'تمام كده، مكتب الحسابات هيكون في انتظارك في الميعاد اللي حددته. تشرفنا هنكون في استقبالك.',
      'per_unit_selection_note': 'اختيارك بيغطي أكتر من وحدة — كل وحدة هتاخد إيصالها الخاص بيها.',
      'pay_partial_toggle': 'ادفع جزء من المبلغ',
      'pay_partial_amount_label': 'المبلغ اللي هتدفعه دلوقتي',
      'remaining_due_date_label': 'باقي المبلغ هيتسدد بحلول',
      'pay_partial_cap_note': 'بحد أقصى 5 أيام من النهاردة. لمدة أطول، تواصل مع مكتب الحسابات.',
      'pay_partial_invalid_amount': 'ادخل مبلغ أكبر من صفر وميزدش عن الإجمالي.',
      'pay_partial_date_required': 'اختار هتسدد الباقي إمتى.',
      'pick_date': 'اختار تاريخ',
      'add_installment': 'إضافة دفعة',
      'submit_request': 'إرسال الطلب',
      'cancel': 'إلغاء',
      'close_button': 'إغلاق',
      'legend_issued': 'تاريخ صدور المديونية',
      'legend_today': 'اليوم',
      'legend_selected': 'المحدد',
      'profile_title': 'البروفايل',
      'settings_title': 'الإعدادات',
      'payment_methods_title': 'وسائل الدفع',
      'contact_us_title': 'تواصل معنا',
      'about_title': 'عن التطبيق',
      'language_title': 'اللغة',
      'role_label': 'الصفة',
      'village_label': 'القرية',
      'fullname_hint': 'الاسم بالكامل',
      'save_button': 'حفظ',
      'profile_saved': 'تم تحديث البروفايل.',
      'payment_methods_coming_soon': 'جاري تجهيز الدفع الإلكتروني. هتقدر تضيف وسيلة دفع من هنا قريبًا.',
      'contact_us_sent': 'تم إرسال رسالتك — هنتواصل معاك قريب.',
      'contact_us_no_unit': 'مفيش وحدة مرتبطة بحسابك لسه.',
      'load_unit_error': "تعذر تحميل بيانات وحدتك. تأكد من الاتصال بالإنترنت وحاول مرة أخرى.",
      'retry_button': "إعادة المحاولة",
      'contact_us_subject_hint': 'الموضوع',
      'contact_us_message_hint': 'رسالتك',
      'about_version': 'الإصدار 1.0.0',
      'about_description': 'أونر كونكت بيساعدك تدير وحدتك وفواتيرك وطلباتك في القرية — كل حاجة في مكان واحد.',
      'notifications_title': 'الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_notifications_yet': 'لا توجد إشعارات حتى الآن',
      'payment_history_title': 'سجل المدفوعات',
      'download_receipt': 'تحميل الإيصال',
      'no_payments_yet': 'لا توجد مدفوعات',
      'receipt_no_label': 'رقم الإيصال',
      'filter_by_month': 'تصفية بالشهر',
      'clear_filter': 'إلغاء التصفية',
      'combined_total': 'إجمالي المستحقات الموحد',
      'per_unit_breakdown': 'التفاصيل حسب الوحدة',
      'clearance_title': 'مخالصة نهاية العقد',
      'generate_clearance': 'إصدار المخالصة',
      'as_of_date': 'حتى تاريخ',
      'clearance_clear_status': 'لا توجد مستحقات مالية على الوحدة',
      'clearance_outstanding_status': 'الرصيد المستحق',
      'clearance_history': 'المخالصات السابقة',
      'no_clearance_yet': 'لا توجد مخالصات سابقة',
      'select_unit': 'اختر الوحدة',
      'select_resort_title': 'اختر قريتك',
      'select_resort_subtitle': 'اختار القرية اللي وحدتك فيها',
      'search_resort_hint': 'دور على قريتك',
      'no_resorts_found': 'مفيش قرى متاحة بالاسم ده',
      'welcome_to_resort': 'أهلاً بيك في',
      'welcome_resort_subtitle': 'يسعدنا وجودك معانا',
      'retry': 'حاول تاني',
    },
    'de': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Gebühren der Einheit',
      'tickets_title': 'Support & Wartung',
      'passes_title': 'Tor- & Strandausweise',
      'pay_now': 'Ausgewählte Gebühren bezahlen',
      'create_ticket': 'Neue Support-Anfrage',
      'select_issue_type': 'Worum geht es?',
      'category_electrician': 'Elektriker',
      'category_plumber': 'Klempner',
      'category_carpenter': 'Schreiner',
      'category_satellite': 'Satellitentechniker',
      'category_gardening': 'Garten- & Landschaftspflege',
      'category_pest_control': 'Schädlingsbekämpfung',
      'issue_details_hint': 'Weitere Details (optional)',
      'ticket_submitted': 'Ihre Anfrage wurde gesendet — unser Team meldet sich bald.',
      'create_pass': 'Neuer Besucherausweis',
      'no_charges': 'Keine Gebühren gefunden',
      'no_tickets': 'Keine Support-Tickets gefunden',
      'no_passes': 'Keine Torausweise gefunden',
      'status_published': 'Veröffentlicht',
      'status_paid': 'Bezahlt',
      'status_unpaid': 'Unbezahlt',
      'unit': 'Einheit',
      'amount': 'Betrag',
      'remaining': 'Verbleibend',
      'details': 'Details',
      'qr_code': 'Eingangs-QR-Code anzeigen',
      'pass_code_label': 'Code',
      'splash_tagline': 'Intelligentes Resort-Leben, vernetzt',
      'splash_checking': 'Sitzung wird überprüft…',
      'login_title': 'Willkommen bei OwnerConnect',
      'login_subtitle': 'Wählen Sie Ihr Land und geben Sie Ihre Telefonnummer ein, um fortzufahren',
      'phone_hint': 'Telefonnummer',
      'continue_button': 'Weiter',
      'invalid_phone': 'Bitte geben Sie eine gültige Telefonnummer ein',
      'dev_bypass_button': 'Entwickler-Testanmeldung',
      'otp_title': 'Bestätigungscode',
      'otp_subtitle': 'Geben Sie den 6-stelligen Code ein, gesendet an',
      'verify_button': 'Bestätigen',
      'resend_code': 'Code erneut senden',
      'resend_in': 'Code erneut senden in',
      'pending_resort_title': 'Konto noch nicht verknüpft',
      'pending_resort_message':
          'Ihr Konto existiert, ist aber noch keinem Resort/Dorf zugeordnet. Bitte wenden Sie sich an Ihre Resortverwaltung.',
      'logout': 'Abmelden',
      'or_divider': 'oder',
      'or_continue_another_way': 'oder auf andere Weise fortfahren',
      'continue_with_google': 'Mit Google fortfahren',
      'continue_with_email': 'Mit E-Mail fortfahren',
      'email_hint': 'E-Mail',
      'password_hint': 'Passwort',
      'sign_in_button': 'Anmelden',
      'register_button': 'Konto erstellen',
      'toggle_to_register': 'Noch kein Konto? Jetzt erstellen',
      'toggle_to_sign_in': 'Bereits ein Konto? Anmelden',
      'link_account_title': 'Konto verknüpfen',
      'link_account_subtitle':
          'Geben Sie die bei Ihrem Resort hinterlegte Telefonnummer und den vom Personal erhaltenen Aktivierungscode ein.',
      'activation_code_hint': 'Aktivierungscode',
      'role_owner': 'Eigentümer',
      'role_tenant': 'Mieter',
      'checkout_title': 'Kasse',
      'payment_successful': 'Zahlung erfolgreich',
      'payment_failed': 'Zahlung fehlgeschlagen',
      'order_id': 'Bestell-ID',
      'payment_processed_success': 'Ihre Zahlung wurde erfolgreich verarbeitet.',
      'payment_options_title': 'Zahlungsoptionen',
      'pay_online_option': 'Online bezahlen',
      'pay_online_subtitle': 'Jetzt mit Karte über das Zahlungsportal bezahlen.',
      'defer_option': 'Zahlung aufschieben',
      'defer_subtitle': 'Fälligkeitsdatum um bis zu 3 Tage verschieben.',
      'defer_multi_charge_note': 'Aufschub und Ratenzahlungspläne sind nur für eine Gebühr gleichzeitig verfügbar — wählen Sie eine einzelne Gebühr aus.',
      'deferred_to_label': 'Aufgeschoben auf',
      'payment_plan_option': 'Ratenzahlungsplan beantragen',
      'payment_plan_subtitle': 'Raten für einen hohen Betrag vorschlagen — erfordert Genehmigung des Buchhalters.',
      'payment_plan_pending': 'Ihr Antrag auf einen Ratenzahlungsplan wurde eingereicht und wartet auf Genehmigung.',
      'pay_at_office_option': 'Bar im Buchhaltungsbüro bezahlen',
      'pay_at_office_subtitle': 'Wählen Sie ein Datum, und wir informieren das Büro über Ihren Besuch.',
      'pay_at_office_subject': 'Barzahlung im Buchhaltungsbüro',
      'pay_at_office_description': 'Der Eigentümer zahlt bar im Buchhaltungsbüro am',
      'pay_at_office_confirmed': 'Alles bereit — das Buchhaltungsbüro erwartet Sie am gewählten Termin. Wir freuen uns auf Sie.',
      'per_unit_selection_note': 'Ihre Auswahl umfasst mehrere Einheiten — jede Einheit erhält eine eigene Quittung.',
      'pay_partial_toggle': 'Teilbetrag bezahlen',
      'pay_partial_amount_label': 'Jetzt zu zahlender Betrag',
      'remaining_due_date_label': 'Restbetrag fällig bis',
      'pay_partial_cap_note': 'Bis zu 5 Tage ab heute. Für längere Fristen wenden Sie sich an das Buchhaltungsbüro.',
      'pay_partial_invalid_amount': 'Geben Sie einen Betrag größer als 0 und nicht mehr als die Gesamtsumme ein.',
      'pay_partial_date_required': 'Wählen Sie, wann Sie den Rest bezahlen werden.',
      'pick_date': 'Datum auswählen',
      'add_installment': 'Rate hinzufügen',
      'submit_request': 'Antrag senden',
      'cancel': 'Abbrechen',
      'close_button': 'Schließen',
      'legend_issued': 'Schuld ausgestellt',
      'legend_today': 'Heute',
      'legend_selected': 'Ausgewählt',
      'profile_title': 'Profil',
      'settings_title': 'Einstellungen',
      'payment_methods_title': 'Zahlungsmethoden',
      'contact_us_title': 'Kontakt',
      'about_title': 'Über die App',
      'language_title': 'Sprache',
      'role_label': 'Rolle',
      'village_label': 'Dorf',
      'fullname_hint': 'Vollständiger Name',
      'save_button': 'Speichern',
      'profile_saved': 'Profil aktualisiert.',
      'payment_methods_coming_soon': 'Die Online-Zahlungseinrichtung wird vorbereitet. Bald können Sie hier eine Zahlungsmethode hinzufügen.',
      'contact_us_sent': 'Ihre Nachricht wurde gesendet — wir melden uns bald.',
      'contact_us_no_unit': 'Ihrem Konto ist noch keine Einheit zugeordnet.',
      'load_unit_error': "Ihre Einheit konnte nicht geladen werden. Bitte Verbindung prüfen und erneut versuchen.",
      'retry_button': "Erneut versuchen",
      'contact_us_subject_hint': 'Betreff',
      'contact_us_message_hint': 'Ihre Nachricht',
      'about_version': 'Version 1.0.0',
      'about_description': 'OwnerConnect hilft Ihnen, Ihre Einheit, Gebühren und Anfragen im Resort zu verwalten — alles an einem Ort.',
      'notifications_title': 'Benachrichtigungen',
      'mark_all_read': 'Alle als gelesen markieren',
      'no_notifications_yet': 'Noch keine Benachrichtigungen',
      'payment_history_title': 'Zahlungsverlauf',
      'download_receipt': 'Quittung herunterladen',
      'no_payments_yet': 'Keine Zahlungen gefunden',
      'receipt_no_label': 'Belegnummer',
      'filter_by_month': 'Nach Monat filtern',
      'clear_filter': 'Filter zurücksetzen',
      'combined_total': 'Gesamtschuld (kombiniert)',
      'per_unit_breakdown': 'Aufschlüsselung nach Einheit',
      'clearance_title': 'Unbedenklichkeitsbescheinigung',
      'generate_clearance': 'Bescheinigung ausstellen',
      'as_of_date': 'Stand vom',
      'clearance_clear_status': 'Keine offenen Forderungen',
      'clearance_outstanding_status': 'Offener Saldo',
      'clearance_history': 'Frühere Bescheinigungen',
      'no_clearance_yet': 'Noch keine Bescheinigungen',
      'select_unit': 'Einheit auswählen',
    },
    'fr': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Charges de l\'unité',
      'tickets_title': 'Support & Maintenance',
      'passes_title': 'Laissez-passer portail & plage',
      'pay_now': 'Payer les charges sélectionnées',
      'create_ticket': 'Nouvelle demande d\'assistance',
      'select_issue_type': 'De quoi s\'agit-il ?',
      'category_electrician': 'Électricien',
      'category_plumber': 'Plombier',
      'category_carpenter': 'Menuisier',
      'category_satellite': 'Technicien satellite',
      'category_gardening': 'Jardinage & agriculture',
      'category_pest_control': 'Lutte antiparasitaire',
      'issue_details_hint': 'Ajouter des détails (facultatif)',
      'ticket_submitted': 'Votre demande a été envoyée — notre équipe vous contactera bientôt.',
      'create_pass': 'Nouveau laissez-passer visiteur',
      'no_charges': 'Aucune charge trouvée',
      'no_tickets': 'Aucun ticket d\'assistance trouvé',
      'no_passes': 'Aucun laissez-passer trouvé',
      'status_published': 'Publiée',
      'status_paid': 'Payée',
      'status_unpaid': 'Impayée',
      'unit': 'Unité',
      'amount': 'Montant',
      'remaining': 'Restant',
      'details': 'Détails',
      'qr_code': 'Afficher le QR code d\'entrée',
      'pass_code_label': 'Code',
      'splash_tagline': 'La vie intelligente en résidence, connectée',
      'splash_checking': 'Vérification de votre session…',
      'login_title': 'Bienvenue sur OwnerConnect',
      'login_subtitle': 'Sélectionnez votre pays et saisissez votre numéro de téléphone pour continuer',
      'phone_hint': 'Numéro de téléphone',
      'continue_button': 'Continuer',
      'invalid_phone': 'Veuillez saisir un numéro de téléphone valide',
      'dev_bypass_button': 'Connexion test développeur',
      'otp_title': 'Code de vérification',
      'otp_subtitle': 'Saisissez le code à 6 chiffres envoyé au',
      'verify_button': 'Vérifier',
      'resend_code': 'Renvoyer le code',
      'resend_in': 'Renvoyer le code dans',
      'pending_resort_title': 'Compte pas encore lié',
      'pending_resort_message':
          'Votre compte existe mais n\'est pas encore lié à une résidence/village. Veuillez contacter l\'administration de votre résidence.',
      'logout': 'Déconnexion',
      'or_divider': 'ou',
      'or_continue_another_way': 'ou continuer autrement',
      'continue_with_google': 'Continuer avec Google',
      'continue_with_email': 'Continuer avec l\'e-mail',
      'email_hint': 'E-mail',
      'password_hint': 'Mot de passe',
      'sign_in_button': 'Se connecter',
      'register_button': 'Créer un compte',
      'toggle_to_register': 'Pas de compte ? Créez-en un',
      'toggle_to_sign_in': 'Déjà un compte ? Connectez-vous',
      'link_account_title': 'Lier votre compte',
      'link_account_subtitle':
          'Saisissez le numéro de téléphone enregistré auprès de votre résidence et le code d\'activation fourni par le personnel.',
      'activation_code_hint': 'Code d\'activation',
      'role_owner': 'Propriétaire',
      'role_tenant': 'Locataire',
      'checkout_title': 'Paiement',
      'payment_successful': 'Paiement réussi',
      'payment_failed': 'Échec du paiement',
      'order_id': 'Numéro de commande',
      'payment_processed_success': 'Votre paiement a été traité avec succès.',
      'payment_options_title': 'Options de paiement',
      'pay_online_option': 'Payer en ligne',
      'pay_online_subtitle': 'Payez maintenant par carte via la passerelle de paiement.',
      'defer_option': 'Différer le paiement',
      'defer_subtitle': 'Repoussez l\'échéance de jusqu\'à 3 jours.',
      'defer_multi_charge_note': 'Le report et les plans de paiement ne sont disponibles que pour une seule charge à la fois — sélectionnez une seule charge pour les utiliser.',
      'deferred_to_label': 'Reporté au',
      'payment_plan_option': 'Demander un plan de paiement',
      'payment_plan_subtitle': 'Proposez des échéances pour un montant important — nécessite l\'approbation du comptable.',
      'payment_plan_pending': 'Votre demande de plan de paiement a été soumise et est en attente d\'approbation.',
      'pay_at_office_option': 'Payer en espèces au bureau de comptabilité',
      'pay_at_office_subtitle': 'Choisissez une date et nous informerons le bureau de comptabilité de votre venue.',
      'pay_at_office_subject': 'Paiement en espèces au bureau de comptabilité',
      'pay_at_office_description': 'Le propriétaire paiera en espèces au bureau de comptabilité le',
      'pay_at_office_confirmed': 'Tout est prêt — le bureau de comptabilité vous attendra à la date choisie. Ce sera un plaisir de vous accueillir.',
      'per_unit_selection_note': 'Votre sélection couvre plusieurs unités — chaque unité recevra son propre reçu séparé.',
      'pay_partial_toggle': 'Payer un montant partiel',
      'pay_partial_amount_label': 'Montant à payer maintenant',
      'remaining_due_date_label': 'Solde restant dû avant le',
      'pay_partial_cap_note': 'Jusqu\'à 5 jours à partir d\'aujourd\'hui. Pour plus longtemps, contactez le bureau de comptabilité.',
      'pay_partial_invalid_amount': 'Saisissez un montant supérieur à 0 et ne dépassant pas le total.',
      'pay_partial_date_required': 'Choisissez quand vous paierez le reste.',
      'pick_date': 'Choisir une date',
      'add_installment': 'Ajouter une échéance',
      'submit_request': 'Envoyer la demande',
      'cancel': 'Annuler',
      'close_button': 'Fermer',
      'legend_issued': 'Dette émise',
      'legend_today': 'Aujourd\'hui',
      'legend_selected': 'Sélectionné',
      'profile_title': 'Profil',
      'settings_title': 'Paramètres',
      'payment_methods_title': 'Moyens de paiement',
      'contact_us_title': 'Nous contacter',
      'about_title': 'À propos',
      'language_title': 'Langue',
      'role_label': 'Statut',
      'village_label': 'Village',
      'fullname_hint': 'Nom complet',
      'save_button': 'Enregistrer',
      'profile_saved': 'Profil mis à jour.',
      'payment_methods_coming_soon': 'La configuration du paiement en ligne est en cours. Vous pourrez bientôt ajouter un moyen de paiement ici.',
      'contact_us_sent': 'Votre message a été envoyé — nous vous répondrons bientôt.',
      'contact_us_no_unit': 'Aucune unité liée à votre compte pour le moment.',
      'load_unit_error': "Impossible de charger votre unité. Vérifiez votre connexion et réessayez.",
      'retry_button': "Réessayer",
      'contact_us_subject_hint': 'Objet',
      'contact_us_message_hint': 'Votre message',
      'about_version': 'Version 1.0.0',
      'about_description': 'OwnerConnect vous aide à gérer votre unité, vos charges et vos demandes dans votre résidence — le tout au même endroit.',
      'notifications_title': 'Notifications',
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications_yet': 'Aucune notification pour le moment',
      'payment_history_title': 'Historique des paiements',
      'download_receipt': 'Télécharger le reçu',
      'no_payments_yet': 'Aucun paiement trouvé',
      'receipt_no_label': 'N° de reçu',
      'filter_by_month': 'Filtrer par mois',
      'clear_filter': 'Effacer le filtre',
      'combined_total': 'Total dû combiné',
      'per_unit_breakdown': 'Répartition par unité',
      'clearance_title': 'Quitus / Attestation de solde',
      'generate_clearance': 'Délivrer l\'attestation',
      'as_of_date': 'À la date du',
      'clearance_clear_status': 'Aucun montant dû',
      'clearance_outstanding_status': 'Solde impayé',
      'clearance_history': 'Attestations précédentes',
      'no_clearance_yet': 'Aucune attestation pour le moment',
      'select_unit': 'Sélectionner l\'unité',
    },
    'it': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Spese dell\'unità',
      'tickets_title': 'Assistenza e Manutenzione',
      'passes_title': 'Pass cancello e spiaggia',
      'pay_now': 'Paga le spese selezionate',
      'create_ticket': 'Nuova richiesta di assistenza',
      'select_issue_type': 'Qual è il problema?',
      'category_electrician': 'Elettricista',
      'category_plumber': 'Idraulico',
      'category_carpenter': 'Falegname',
      'category_satellite': 'Tecnico satellitare',
      'category_gardening': 'Giardinaggio e agricoltura',
      'category_pest_control': 'Disinfestazione',
      'issue_details_hint': 'Aggiungi dettagli (facoltativo)',
      'ticket_submitted': 'La tua richiesta è stata inviata — il nostro team ti contatterà presto.',
      'create_pass': 'Nuovo pass visitatore',
      'no_charges': 'Nessuna spesa trovata',
      'no_tickets': 'Nessun ticket di assistenza trovato',
      'no_passes': 'Nessun pass trovato',
      'status_published': 'Pubblicata',
      'status_paid': 'Pagata',
      'status_unpaid': 'Non pagata',
      'unit': 'Unità',
      'amount': 'Importo',
      'remaining': 'Rimanente',
      'details': 'Dettagli',
      'qr_code': 'Mostra QR code d\'ingresso',
      'pass_code_label': 'Codice',
      'splash_tagline': 'Vita smart in resort, connessa',
      'splash_checking': 'Verifica della sessione…',
      'login_title': 'Benvenuto su OwnerConnect',
      'login_subtitle': 'Seleziona il tuo paese e inserisci il numero di telefono per continuare',
      'phone_hint': 'Numero di telefono',
      'continue_button': 'Continua',
      'invalid_phone': 'Inserisci un numero di telefono valido',
      'dev_bypass_button': 'Accesso di test sviluppatore',
      'otp_title': 'Codice di verifica',
      'otp_subtitle': 'Inserisci il codice a 6 cifre inviato a',
      'verify_button': 'Verifica',
      'resend_code': 'Invia di nuovo il codice',
      'resend_in': 'Reinvia il codice tra',
      'pending_resort_title': 'Account non ancora collegato',
      'pending_resort_message':
          'Il tuo account esiste ma non è ancora collegato a un resort/villaggio. Contatta l\'amministrazione del tuo resort.',
      'logout': 'Esci',
      'or_divider': 'oppure',
      'or_continue_another_way': 'oppure continua in un altro modo',
      'continue_with_google': 'Continua con Google',
      'continue_with_email': 'Continua con l\'e-mail',
      'email_hint': 'E-mail',
      'password_hint': 'Password',
      'sign_in_button': 'Accedi',
      'register_button': 'Crea account',
      'toggle_to_register': 'Non hai un account? Creane uno',
      'toggle_to_sign_in': 'Hai già un account? Accedi',
      'link_account_title': 'Collega il tuo account',
      'link_account_subtitle':
          'Inserisci il numero di telefono registrato presso il tuo resort e il codice di attivazione fornito dallo staff.',
      'activation_code_hint': 'Codice di attivazione',
      'role_owner': 'Proprietario',
      'role_tenant': 'Inquilino',
      'checkout_title': 'Pagamento',
      'payment_successful': 'Pagamento riuscito',
      'payment_failed': 'Pagamento non riuscito',
      'order_id': 'ID ordine',
      'payment_processed_success': 'Il tuo pagamento è stato elaborato con successo.',
      'payment_options_title': 'Opzioni di pagamento',
      'pay_online_option': 'Paga online',
      'pay_online_subtitle': 'Paga subito con carta tramite il gateway di pagamento.',
      'defer_option': 'Rinvia il pagamento',
      'defer_subtitle': 'Posticipa la scadenza fino a 3 giorni.',
      'defer_multi_charge_note': 'Il rinvio e i piani di pagamento sono disponibili solo per una spesa alla volta — seleziona una singola spesa per usarli.',
      'deferred_to_label': 'Rinviato al',
      'payment_plan_option': 'Richiedi un piano di pagamento',
      'payment_plan_subtitle': 'Proponi rate per un importo elevato — richiede l\'approvazione del contabile.',
      'payment_plan_pending': 'La tua richiesta di piano di pagamento è stata inviata ed è in attesa di approvazione.',
      'pay_at_office_option': 'Paga in contanti presso l\'ufficio contabilità',
      'pay_at_office_subtitle': 'Scegli una data e avviseremo l\'ufficio contabilità del tuo arrivo.',
      'pay_at_office_subject': 'Pagamento in contanti presso l\'ufficio contabilità',
      'pay_at_office_description': 'Il proprietario pagherà in contanti presso l\'ufficio contabilità il',
      'pay_at_office_confirmed': 'Tutto pronto — l\'ufficio contabilità ti aspetterà alla data scelta. Sarà un piacere accoglierti.',
      'per_unit_selection_note': 'La tua selezione copre più unità — ogni unità riceverà una propria ricevuta separata.',
      'pay_partial_toggle': 'Paga un importo parziale',
      'pay_partial_amount_label': 'Importo da pagare ora',
      'remaining_due_date_label': 'Saldo rimanente dovuto entro',
      'pay_partial_cap_note': 'Fino a 5 giorni da oggi. Per periodi più lunghi, contatta l\'ufficio contabilità.',
      'pay_partial_invalid_amount': 'Inserisci un importo maggiore di 0 e non superiore al totale.',
      'pay_partial_date_required': 'Scegli quando pagherai il resto.',
      'pick_date': 'Scegli una data',
      'add_installment': 'Aggiungi rata',
      'submit_request': 'Invia richiesta',
      'cancel': 'Annulla',
      'close_button': 'Chiudi',
      'legend_issued': 'Debito emesso',
      'legend_today': 'Oggi',
      'legend_selected': 'Selezionato',
      'profile_title': 'Profilo',
      'settings_title': 'Impostazioni',
      'payment_methods_title': 'Metodi di pagamento',
      'contact_us_title': 'Contattaci',
      'about_title': 'Informazioni',
      'language_title': 'Lingua',
      'role_label': 'Ruolo',
      'village_label': 'Villaggio',
      'fullname_hint': 'Nome completo',
      'save_button': 'Salva',
      'profile_saved': 'Profilo aggiornato.',
      'payment_methods_coming_soon': 'La configurazione dei pagamenti online è in corso. Presto potrai aggiungere qui un metodo di pagamento.',
      'contact_us_sent': 'Il tuo messaggio è stato inviato — ti risponderemo presto.',
      'contact_us_no_unit': 'Nessuna unità ancora collegata al tuo account.',
      'load_unit_error': "Impossibile caricare la tua unità. Controlla la connessione e riprova.",
      'retry_button': "Riprova",
      'contact_us_subject_hint': 'Oggetto',
      'contact_us_message_hint': 'Il tuo messaggio',
      'about_version': 'Versione 1.0.0',
      'about_description': 'OwnerConnect ti aiuta a gestire la tua unità, le spese e le richieste presso il tuo resort — tutto in un unico posto.',
      'notifications_title': 'Notifiche',
      'mark_all_read': 'Segna tutte come lette',
      'no_notifications_yet': 'Ancora nessuna notifica',
      'payment_history_title': 'Cronologia pagamenti',
      'download_receipt': 'Scarica ricevuta',
      'no_payments_yet': 'Nessun pagamento trovato',
      'receipt_no_label': 'N. ricevuta',
      'filter_by_month': 'Filtra per mese',
      'clear_filter': 'Rimuovi filtro',
      'combined_total': 'Totale dovuto combinato',
      'per_unit_breakdown': 'Dettaglio per unità',
      'clearance_title': 'Attestato di saldo',
      'generate_clearance': 'Emetti attestato di saldo',
      'as_of_date': 'Alla data del',
      'clearance_clear_status': 'Nessun importo dovuto',
      'clearance_outstanding_status': 'Saldo dovuto',
      'clearance_history': 'Attestati precedenti',
      'no_clearance_yet': 'Ancora nessun attestato',
      'select_unit': 'Seleziona unità',
    },
    'ru': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Начисления по объекту',
      'tickets_title': 'Поддержка и обслуживание',
      'passes_title': 'Пропуска на въезд и пляж',
      'pay_now': 'Оплатить выбранные начисления',
      'create_ticket': 'Новая заявка в поддержку',
      'select_issue_type': 'В чём проблема?',
      'category_electrician': 'Электрик',
      'category_plumber': 'Сантехник',
      'category_carpenter': 'Плотник',
      'category_satellite': 'Специалист по спутниковому ТВ',
      'category_gardening': 'Садовые и сельхоз работы',
      'category_pest_control': 'Дезинсекция',
      'issue_details_hint': 'Добавьте детали (необязательно)',
      'ticket_submitted': 'Ваш запрос отправлен — наша команда скоро с вами свяжется.',
      'create_pass': 'Новый пропуск для гостя',
      'no_charges': 'Начисления не найдены',
      'no_tickets': 'Заявки в поддержку не найдены',
      'no_passes': 'Пропуска не найдены',
      'status_published': 'Опубликовано',
      'status_paid': 'Оплачено',
      'status_unpaid': 'Не оплачено',
      'unit': 'Объект',
      'amount': 'Сумма',
      'remaining': 'Остаток',
      'details': 'Подробности',
      'qr_code': 'Показать QR-код для входа',
      'pass_code_label': 'Код',
      'splash_tagline': 'Умная жизнь в резорте, на связи',
      'splash_checking': 'Проверка вашей сессии…',
      'login_title': 'Добро пожаловать в OwnerConnect',
      'login_subtitle': 'Выберите страну и введите номер телефона, чтобы продолжить',
      'phone_hint': 'Номер телефона',
      'continue_button': 'Продолжить',
      'invalid_phone': 'Пожалуйста, введите корректный номер телефона',
      'dev_bypass_button': 'Тестовый вход разработчика',
      'otp_title': 'Код подтверждения',
      'otp_subtitle': 'Введите 6-значный код, отправленный на',
      'verify_button': 'Подтвердить',
      'resend_code': 'Отправить код повторно',
      'resend_in': 'Повторная отправка через',
      'pending_resort_title': 'Аккаунт ещё не привязан',
      'pending_resort_message':
          'Ваш аккаунт создан, но пока не привязан к курорту/посёлку. Пожалуйста, свяжитесь с администрацией курорта.',
      'logout': 'Выйти',
      'or_divider': 'или',
      'or_continue_another_way': 'или продолжить другим способом',
      'continue_with_google': 'Продолжить через Google',
      'continue_with_email': 'Продолжить через e-mail',
      'email_hint': 'Эл. почта',
      'password_hint': 'Пароль',
      'sign_in_button': 'Войти',
      'register_button': 'Создать аккаунт',
      'toggle_to_register': 'Нет аккаунта? Создать',
      'toggle_to_sign_in': 'Уже есть аккаунт? Войти',
      'link_account_title': 'Привязать аккаунт',
      'link_account_subtitle':
          'Введите номер телефона, указанный в вашем курорте, и код активации, выданный сотрудником.',
      'activation_code_hint': 'Код активации',
      'role_owner': 'Владелец',
      'role_tenant': 'Арендатор',
      'checkout_title': 'Оплата',
      'payment_successful': 'Оплата прошла успешно',
      'payment_failed': 'Оплата не выполнена',
      'order_id': 'Номер заказа',
      'payment_processed_success': 'Ваш платёж успешно обработан.',
      'payment_options_title': 'Способы оплаты',
      'pay_online_option': 'Оплатить онлайн',
      'pay_online_subtitle': 'Оплатите сейчас картой через платёжный шлюз.',
      'defer_option': 'Отложить платёж',
      'defer_subtitle': 'Перенести срок оплаты до 3 дней.',
      'defer_multi_charge_note': 'Отсрочка и планы оплаты доступны только для одного начисления за раз — выберите одно начисление, чтобы ими воспользоваться.',
      'deferred_to_label': 'Отложено до',
      'payment_plan_option': 'Запросить план оплаты',
      'payment_plan_subtitle': 'Предложите рассрочку для крупной суммы — требуется одобрение бухгалтера.',
      'payment_plan_pending': 'Ваш запрос на план оплаты отправлен и ожидает одобрения бухгалтера.',
      'pay_at_office_option': 'Оплатить наличными в бухгалтерии',
      'pay_at_office_subtitle': 'Выберите дату, и мы сообщим бухгалтерии о вашем визите.',
      'pay_at_office_subject': 'Оплата наличными в бухгалтерии',
      'pay_at_office_description': 'Владелец оплатит наличными в бухгалтерии',
      'pay_at_office_confirmed': 'Всё готово — бухгалтерия будет ждать вас в выбранную дату. Будем рады вас видеть.',
      'per_unit_selection_note': 'Ваш выбор охватывает несколько объектов — на каждый объект будет выдана отдельная квитанция.',
      'pay_partial_toggle': 'Оплатить частично',
      'pay_partial_amount_label': 'Сумма к оплате сейчас',
      'remaining_due_date_label': 'Остаток должен быть оплачен до',
      'pay_partial_cap_note': 'До 5 дней с сегодняшнего дня. Для большего срока обратитесь в бухгалтерию.',
      'pay_partial_invalid_amount': 'Введите сумму больше 0 и не превышающую общую сумму.',
      'pay_partial_date_required': 'Выберите, когда вы оплатите остаток.',
      'pick_date': 'Выбрать дату',
      'add_installment': 'Добавить платёж',
      'submit_request': 'Отправить запрос',
      'cancel': 'Отмена',
      'close_button': 'Закрыть',
      'legend_issued': 'Начислен долг',
      'legend_today': 'Сегодня',
      'legend_selected': 'Выбрано',
      'profile_title': 'Профиль',
      'settings_title': 'Настройки',
      'payment_methods_title': 'Способы оплаты',
      'contact_us_title': 'Связаться с нами',
      'about_title': 'О приложении',
      'language_title': 'Язык',
      'role_label': 'Статус',
      'village_label': 'Посёлок',
      'fullname_hint': 'Полное имя',
      'save_button': 'Сохранить',
      'profile_saved': 'Профиль обновлён.',
      'payment_methods_coming_soon': 'Настройка онлайн-оплаты в процессе. Скоро вы сможете добавить способ оплаты здесь.',
      'contact_us_sent': 'Ваше сообщение отправлено — мы скоро свяжемся с вами.',
      'contact_us_no_unit': 'К вашему аккаунту пока не привязан объект.',
      'load_unit_error': "Не удалось загрузить данные объекта. Проверьте подключение и повторите попытку.",
      'retry_button': "Повторить",
      'contact_us_subject_hint': 'Тема',
      'contact_us_message_hint': 'Ваше сообщение',
      'about_version': 'Версия 1.0.0',
      'about_description': 'OwnerConnect помогает управлять вашим объектом, начислениями и заявками в вашем курорте — всё в одном месте.',
      'notifications_title': 'Уведомления',
      'mark_all_read': 'Отметить все как прочитанные',
      'no_notifications_yet': 'Пока нет уведомлений',
      'payment_history_title': 'История платежей',
      'download_receipt': 'Скачать квитанцию',
      'no_payments_yet': 'Платежи не найдены',
      'receipt_no_label': '№ квитанции',
      'filter_by_month': 'Фильтр по месяцу',
      'clear_filter': 'Сбросить фильтр',
      'combined_total': 'Общая сумма задолженности',
      'per_unit_breakdown': 'Разбивка по объектам',
      'clearance_title': 'Справка об отсутствии задолженности',
      'generate_clearance': 'Выдать справку',
      'as_of_date': 'По состоянию на',
      'clearance_clear_status': 'Задолженность отсутствует',
      'clearance_outstanding_status': 'Непогашенный остаток',
      'clearance_history': 'Предыдущие справки',
      'no_clearance_yet': 'Справок пока нет',
      'select_unit': 'Выбрать объект',
    },
    'uk': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Нарахування по об\'єкту',
      'tickets_title': 'Підтримка та обслуговування',
      'passes_title': 'Перепустки на в\'їзд і пляж',
      'pay_now': 'Оплатити обрані нарахування',
      'create_ticket': 'Нова заявка в підтримку',
      'select_issue_type': 'У чому проблема?',
      'category_electrician': 'Електрик',
      'category_plumber': 'Сантехнік',
      'category_carpenter': 'Столяр',
      'category_satellite': 'Спеціаліст із супутникового ТБ',
      'category_gardening': 'Садові та сільгосп роботи',
      'category_pest_control': 'Дезінсекція',
      'issue_details_hint': 'Додайте деталі (необов\'язково)',
      'ticket_submitted': 'Ваш запит надіслано — наша команда скоро зв\'яжеться з вами.',
      'create_pass': 'Нова перепустка для гостя',
      'no_charges': 'Нарахувань не знайдено',
      'no_tickets': 'Заявок у підтримку не знайдено',
      'no_passes': 'Перепусток не знайдено',
      'status_published': 'Опубліковано',
      'status_paid': 'Оплачено',
      'status_unpaid': 'Не оплачено',
      'unit': 'Об\'єкт',
      'amount': 'Сума',
      'remaining': 'Залишок',
      'details': 'Деталі',
      'qr_code': 'Показати QR-код для входу',
      'pass_code_label': 'Код',
      'splash_tagline': 'Розумне життя в резорті, на зв\'язку',
      'splash_checking': 'Перевірка вашої сесії…',
      'login_title': 'Ласкаво просимо до OwnerConnect',
      'login_subtitle': 'Виберіть країну та введіть номер телефону, щоб продовжити',
      'phone_hint': 'Номер телефону',
      'continue_button': 'Продовжити',
      'invalid_phone': 'Будь ласка, введіть коректний номер телефону',
      'dev_bypass_button': 'Тестовий вхід розробника',
      'otp_title': 'Код підтвердження',
      'otp_subtitle': 'Введіть 6-значний код, надісланий на',
      'verify_button': 'Підтвердити',
      'resend_code': 'Надіслати код повторно',
      'resend_in': 'Повторне надсилання через',
      'pending_resort_title': 'Акаунт ще не прив\'язано',
      'pending_resort_message':
          'Ваш акаунт створено, але він ще не прив\'язаний до курорту/селища. Будь ласка, зв\'яжіться з адміністрацією курорту.',
      'logout': 'Вийти',
      'or_divider': 'або',
      'or_continue_another_way': 'або продовжити іншим способом',
      'continue_with_google': 'Продовжити через Google',
      'continue_with_email': 'Продовжити через e-mail',
      'email_hint': 'Ел. пошта',
      'password_hint': 'Пароль',
      'sign_in_button': 'Увійти',
      'register_button': 'Створити акаунт',
      'toggle_to_register': 'Немає акаунту? Створити',
      'toggle_to_sign_in': 'Вже є акаунт? Увійти',
      'link_account_title': 'Прив\'язати акаунт',
      'link_account_subtitle':
          'Введіть номер телефону, зареєстрований у вашому курорті, та код активації, наданий співробітником.',
      'activation_code_hint': 'Код активації',
      'role_owner': 'Власник',
      'role_tenant': 'Орендар',
      'checkout_title': 'Оплата',
      'payment_successful': 'Оплату успішно виконано',
      'payment_failed': 'Оплата не вдалася',
      'order_id': 'Номер замовлення',
      'payment_processed_success': 'Ваш платіж успішно оброблено.',
      'payment_options_title': 'Способи оплати',
      'pay_online_option': 'Оплатити онлайн',
      'pay_online_subtitle': 'Оплатіть зараз карткою через платіжний шлюз.',
      'defer_option': 'Відкласти платіж',
      'defer_subtitle': 'Перенести термін оплати до 3 днів.',
      'defer_multi_charge_note': 'Відстрочення та плани оплати доступні лише для одного нарахування за раз — виберіть одне нарахування, щоб ними скористатися.',
      'deferred_to_label': 'Відкладено до',
      'payment_plan_option': 'Запросити план оплати',
      'payment_plan_subtitle': 'Запропонуйте розстрочку для великої суми — потрібне схвалення бухгалтера.',
      'payment_plan_pending': 'Ваш запит на план оплати надіслано, він очікує на схвалення бухгалтера.',
      'pay_at_office_option': 'Оплатити готівкою в бухгалтерії',
      'pay_at_office_subtitle': 'Виберіть дату, і ми повідомимо бухгалтерію про ваш візит.',
      'pay_at_office_subject': 'Оплата готівкою в бухгалтерії',
      'pay_at_office_description': 'Власник оплатить готівкою в бухгалтерії',
      'pay_at_office_confirmed': 'Все готово — бухгалтерія чекатиме на вас у обрану дату. Будемо раді вас бачити.',
      'per_unit_selection_note': 'Ваш вибір охоплює кілька об\'єктів — на кожен об\'єкт буде видано окрему квитанцію.',
      'pay_partial_toggle': 'Оплатити частково',
      'pay_partial_amount_label': 'Сума до оплати зараз',
      'remaining_due_date_label': 'Залишок має бути оплачений до',
      'pay_partial_cap_note': 'До 5 днів від сьогодні. Для довшого терміну зверніться до бухгалтерії.',
      'pay_partial_invalid_amount': 'Введіть суму більшу за 0 і не більшу за загальну суму.',
      'pay_partial_date_required': 'Виберіть, коли ви сплатите решту.',
      'pick_date': 'Вибрати дату',
      'add_installment': 'Додати платіж',
      'submit_request': 'Надіслати запит',
      'cancel': 'Скасувати',
      'close_button': 'Закрити',
      'legend_issued': 'Заборгованість нараховано',
      'legend_today': 'Сьогодні',
      'legend_selected': 'Обрано',
      'profile_title': 'Профіль',
      'settings_title': 'Налаштування',
      'payment_methods_title': 'Способи оплати',
      'contact_us_title': 'Зв\'язатися з нами',
      'about_title': 'Про додаток',
      'language_title': 'Мова',
      'role_label': 'Статус',
      'village_label': 'Селище',
      'fullname_hint': 'Повне ім\'я',
      'save_button': 'Зберегти',
      'profile_saved': 'Профіль оновлено.',
      'payment_methods_coming_soon': 'Налаштування онлайн-оплати триває. Незабаром ви зможете додати спосіб оплати тут.',
      'contact_us_sent': 'Ваше повідомлення надіслано — ми скоро зв\'яжемося з вами.',
      'contact_us_no_unit': 'До вашого акаунту ще не прив\'язано об\'єкт.',
      'load_unit_error': "Не вдалося завантажити дані об'єкта. Перевірте з'єднання і спробуйте ще раз.",
      'retry_button': "Повторити",
      'contact_us_subject_hint': 'Тема',
      'contact_us_message_hint': 'Ваше повідомлення',
      'about_version': 'Версія 1.0.0',
      'about_description': 'OwnerConnect допомагає керувати вашим об\'єктом, нарахуваннями та заявками у вашому курорті — все в одному місці.',
      'notifications_title': 'Сповіщення',
      'mark_all_read': 'Позначити всі як прочитані',
      'no_notifications_yet': 'Поки що немає сповіщень',
      'payment_history_title': 'Історія платежів',
      'download_receipt': 'Завантажити квитанцію',
      'no_payments_yet': 'Платежів не знайдено',
      'receipt_no_label': '№ квитанції',
      'filter_by_month': 'Фільтр за місяцем',
      'clear_filter': 'Скинути фільтр',
      'combined_total': 'Загальна сума заборгованості',
      'per_unit_breakdown': 'Розбивка за об\'єктами',
      'clearance_title': 'Довідка про відсутність заборгованості',
      'generate_clearance': 'Видати довідку',
      'as_of_date': 'Станом на',
      'clearance_clear_status': 'Заборгованість відсутня',
      'clearance_outstanding_status': 'Непогашений залишок',
      'clearance_history': 'Попередні довідки',
      'no_clearance_yet': 'Довідок поки немає',
      'select_unit': 'Вибрати об\'єкт',
    },
    'fi': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Huoneiston maksut',
      'tickets_title': 'Tuki ja huolto',
      'passes_title': 'Portti- ja rantaluvat',
      'pay_now': 'Maksa valitut maksut',
      'create_ticket': 'Uusi tukipyyntö',
      'select_issue_type': 'Mistä on kyse?',
      'category_electrician': 'Sähköasentaja',
      'category_plumber': 'Putkimies',
      'category_carpenter': 'Puuseppä',
      'category_satellite': 'Satelliittiasentaja',
      'category_gardening': 'Puutarhanhoito',
      'category_pest_control': 'Tuholaistorjunta',
      'issue_details_hint': 'Lisää tietoja (valinnainen)',
      'ticket_submitted': 'Pyyntösi on lähetetty — tiimimme ottaa sinuun pian yhteyttä.',
      'create_pass': 'Uusi vierailijalupa',
      'no_charges': 'Maksuja ei löytynyt',
      'no_tickets': 'Tukipyyntöjä ei löytynyt',
      'no_passes': 'Lupia ei löytynyt',
      'status_published': 'Julkaistu',
      'status_paid': 'Maksettu',
      'status_unpaid': 'Maksamatta',
      'unit': 'Huoneisto',
      'amount': 'Summa',
      'remaining': 'Jäljellä',
      'details': 'Tiedot',
      'qr_code': 'Näytä sisäänpääsyn QR-koodi',
      'pass_code_label': 'Koodi',
      'splash_tagline': 'Älykästä lomakohde-elämää, yhdistettynä',
      'splash_checking': 'Tarkistetaan istuntoasi…',
      'login_title': 'Tervetuloa OwnerConnectiin',
      'login_subtitle': 'Valitse maasi ja anna puhelinnumerosi jatkaaksesi',
      'phone_hint': 'Puhelinnumero',
      'continue_button': 'Jatka',
      'invalid_phone': 'Anna kelvollinen puhelinnumero',
      'dev_bypass_button': 'Kehittäjän testikirjautuminen',
      'otp_title': 'Vahvistuskoodi',
      'otp_subtitle': 'Anna 6-numeroinen koodi, joka lähetettiin numeroon',
      'verify_button': 'Vahvista',
      'resend_code': 'Lähetä koodi uudelleen',
      'resend_in': 'Lähetä koodi uudelleen',
      'pending_resort_title': 'Tiliä ei vielä yhdistetty',
      'pending_resort_message':
          'Tilisi on olemassa, mutta sitä ei ole vielä yhdistetty lomakohteeseen/kylään. Ota yhteyttä lomakohteen hallintoon.',
      'logout': 'Kirjaudu ulos',
      'or_divider': 'tai',
      'or_continue_another_way': 'tai jatka toisella tavalla',
      'continue_with_google': 'Jatka Googlella',
      'continue_with_email': 'Jatka sähköpostilla',
      'email_hint': 'Sähköposti',
      'password_hint': 'Salasana',
      'sign_in_button': 'Kirjaudu sisään',
      'register_button': 'Luo tili',
      'toggle_to_register': 'Eikö sinulla ole tiliä? Luo se',
      'toggle_to_sign_in': 'Onko sinulla jo tili? Kirjaudu sisään',
      'link_account_title': 'Yhdistä tilisi',
      'link_account_subtitle':
          'Anna lomakohteeseesi rekisteröity puhelinnumero ja henkilökunnalta saamasi aktivointikoodi.',
      'activation_code_hint': 'Aktivointikoodi',
      'role_owner': 'Omistaja',
      'role_tenant': 'Vuokralainen',
      'checkout_title': 'Kassa',
      'payment_successful': 'Maksu onnistui',
      'payment_failed': 'Maksu epäonnistui',
      'order_id': 'Tilausnumero',
      'payment_processed_success': 'Maksusi on käsitelty onnistuneesti.',
      'payment_options_title': 'Maksuvaihtoehdot',
      'pay_online_option': 'Maksa verkossa',
      'pay_online_subtitle': 'Maksa nyt kortilla maksuyhdyskäytävän kautta.',
      'defer_option': 'Lykkää maksua',
      'defer_subtitle': 'Siirrä eräpäivää enintään 3 päivällä.',
      'defer_multi_charge_note': 'Lykkäys ja maksusuunnitelmat ovat käytettävissä vain yhdelle maksulle kerrallaan — valitse yksi maksu käyttääksesi niitä.',
      'deferred_to_label': 'Lykätty ajankohtaan',
      'payment_plan_option': 'Pyydä maksusuunnitelmaa',
      'payment_plan_subtitle': 'Ehdota erämaksuja suurelle summalle — vaatii kirjanpitäjän hyväksynnän.',
      'payment_plan_pending': 'Maksusuunnitelmapyyntösi on lähetetty ja odottaa kirjanpitäjän hyväksyntää.',
      'pay_at_office_option': 'Maksa käteisellä kirjanpitotoimistossa',
      'pay_at_office_subtitle': 'Valitse päivämäärä, ja ilmoitamme kirjanpitotoimistolle saapumisestasi.',
      'pay_at_office_subject': 'Käteismaksu kirjanpitotoimistossa',
      'pay_at_office_description': 'Omistaja maksaa käteisellä kirjanpitotoimistossa',
      'pay_at_office_confirmed': 'Kaikki on valmista — kirjanpitotoimisto odottaa sinua valitsemanasi ajankohtana. On ilo ottaa sinut vastaan.',
      'per_unit_selection_note': 'Valintasi kattaa useamman huoneiston — jokainen huoneisto saa oman erillisen kuittinsa.',
      'pay_partial_toggle': 'Maksa osasumma',
      'pay_partial_amount_label': 'Nyt maksettava summa',
      'remaining_due_date_label': 'Jäljellä oleva saldo erääntyy',
      'pay_partial_cap_note': 'Enintään 5 päivää tästä päivästä. Pidempää aikaa varten ota yhteyttä kirjanpitotoimistoon.',
      'pay_partial_invalid_amount': 'Anna summa, joka on suurempi kuin 0 ja enintään kokonaissumma.',
      'pay_partial_date_required': 'Valitse, milloin maksat loput.',
      'pick_date': 'Valitse päivämäärä',
      'add_installment': 'Lisää erä',
      'submit_request': 'Lähetä pyyntö',
      'cancel': 'Peruuta',
      'close_button': 'Sulje',
      'legend_issued': 'Velka kirjattu',
      'legend_today': 'Tänään',
      'legend_selected': 'Valittu',
      'profile_title': 'Profiili',
      'settings_title': 'Asetukset',
      'payment_methods_title': 'Maksutavat',
      'contact_us_title': 'Ota yhteyttä',
      'about_title': 'Tietoa',
      'language_title': 'Kieli',
      'role_label': 'Rooli',
      'village_label': 'Kylä',
      'fullname_hint': 'Koko nimi',
      'save_button': 'Tallenna',
      'profile_saved': 'Profiili päivitetty.',
      'payment_methods_coming_soon': 'Verkkomaksujen käyttöönotto on kesken. Voit pian lisätä maksutavan täältä.',
      'contact_us_sent': 'Viestisi on lähetetty — otamme sinuun pian yhteyttä.',
      'contact_us_no_unit': 'Tiliisi ei ole vielä yhdistetty huoneistoa.',
      'load_unit_error': "Huoneistoasi ei voitu ladata. Tarkista yhteys ja yritä uudelleen.",
      'retry_button': "Yritä uudelleen",
      'contact_us_subject_hint': 'Aihe',
      'contact_us_message_hint': 'Viestisi',
      'about_version': 'Versio 1.0.0',
      'about_description': 'OwnerConnect auttaa sinua hallitsemaan huoneistoasi, maksujasi ja pyyntöjäsi lomakohteessasi — kaikki yhdessä paikassa.',
      'notifications_title': 'Ilmoitukset',
      'mark_all_read': 'Merkitse kaikki luetuiksi',
      'no_notifications_yet': 'Ei vielä ilmoituksia',
      'payment_history_title': 'Maksuhistoria',
      'download_receipt': 'Lataa kuitti',
      'no_payments_yet': 'Maksuja ei löytynyt',
      'receipt_no_label': 'Kuitin numero',
      'filter_by_month': 'Suodata kuukauden mukaan',
      'clear_filter': 'Poista suodatin',
      'combined_total': 'Yhdistetty kokonaisvelka',
      'per_unit_breakdown': 'Erittely huoneistoittain',
      'clearance_title': 'Velattomuustodistus',
      'generate_clearance': 'Myönnä velattomuustodistus',
      'as_of_date': 'Tilanne päivänä',
      'clearance_clear_status': 'Ei avoimia maksuja',
      'clearance_outstanding_status': 'Avoin saldo',
      'clearance_history': 'Aiemmat todistukset',
      'no_clearance_yet': 'Ei vielä todistuksia',
      'select_unit': 'Valitse huoneisto',
    },
    'nb': {
      'app_title': 'OwnerConnect',
      'charges_title': 'Avgifter for enheten',
      'tickets_title': 'Support og vedlikehold',
      'passes_title': 'Port- og strandpass',
      'pay_now': 'Betal valgte avgifter',
      'create_ticket': 'Ny supportforespørsel',
      'select_issue_type': 'Hva gjelder saken?',
      'category_electrician': 'Elektriker',
      'category_plumber': 'Rørlegger',
      'category_carpenter': 'Snekker',
      'category_satellite': 'Satellittekniker',
      'category_gardening': 'Hagearbeid',
      'category_pest_control': 'Skadedyrbekjempelse',
      'issue_details_hint': 'Legg til flere detaljer (valgfritt)',
      'ticket_submitted': 'Forespørselen din er sendt — teamet vårt tar kontakt snart.',
      'create_pass': 'Nytt besøkspass',
      'no_charges': 'Ingen avgifter funnet',
      'no_tickets': 'Ingen supportsaker funnet',
      'no_passes': 'Ingen portpass funnet',
      'status_published': 'Publisert',
      'status_paid': 'Betalt',
      'status_unpaid': 'Ubetalt',
      'unit': 'Enhet',
      'amount': 'Beløp',
      'remaining': 'Gjenstående',
      'details': 'Detaljer',
      'qr_code': 'Vis inngangs-QR-kode',
      'pass_code_label': 'Kode',
      'splash_tagline': 'Smart feriebo-liv, tilkoblet',
      'splash_checking': 'Sjekker økten din…',
      'login_title': 'Velkommen til OwnerConnect',
      'login_subtitle': 'Velg land og skriv inn telefonnummeret ditt for å fortsette',
      'phone_hint': 'Telefonnummer',
      'continue_button': 'Fortsett',
      'invalid_phone': 'Skriv inn et gyldig telefonnummer',
      'dev_bypass_button': 'Utviklerens testpålogging',
      'otp_title': 'Bekreftelseskode',
      'otp_subtitle': 'Skriv inn den 6-sifrede koden sendt til',
      'verify_button': 'Bekreft',
      'resend_code': 'Send koden på nytt',
      'resend_in': 'Send kode på nytt om',
      'pending_resort_title': 'Kontoen er ikke koblet til ennå',
      'pending_resort_message':
          'Kontoen din finnes, men er ikke koblet til et resort/en landsby ennå. Vennligst kontakt resortadministrasjonen.',
      'logout': 'Logg ut',
      'or_divider': 'eller',
      'or_continue_another_way': 'eller fortsett på en annen måte',
      'continue_with_google': 'Fortsett med Google',
      'continue_with_email': 'Fortsett med e-post',
      'email_hint': 'E-post',
      'password_hint': 'Passord',
      'sign_in_button': 'Logg inn',
      'register_button': 'Opprett konto',
      'toggle_to_register': 'Har du ikke en konto? Opprett en',
      'toggle_to_sign_in': 'Har du allerede en konto? Logg inn',
      'link_account_title': 'Koble til kontoen din',
      'link_account_subtitle':
          'Skriv inn telefonnummeret registrert hos resortet ditt og aktiveringskoden fra personalet.',
      'activation_code_hint': 'Aktiveringskode',
      'role_owner': 'Eier',
      'role_tenant': 'Leietaker',
      'checkout_title': 'Kasse',
      'payment_successful': 'Betaling vellykket',
      'payment_failed': 'Betaling mislyktes',
      'order_id': 'Ordre-ID',
      'payment_processed_success': 'Betalingen din er behandlet.',
      'payment_options_title': 'Betalingsalternativer',
      'pay_online_option': 'Betal på nett',
      'pay_online_subtitle': 'Betal nå med kort via betalingsportalen.',
      'defer_option': 'Utsett betaling',
      'defer_subtitle': 'Utsett forfallsdatoen med inntil 3 dager.',
      'defer_multi_charge_note': 'Utsettelse og nedbetalingsplaner er kun tilgjengelig for én avgift om gangen — velg én avgift for å bruke dem.',
      'deferred_to_label': 'Utsatt til',
      'payment_plan_option': 'Be om en nedbetalingsplan',
      'payment_plan_subtitle': 'Foreslå avdrag for et stort beløp — krever godkjenning fra regnskapsfører.',
      'payment_plan_pending': 'Forespørselen om nedbetalingsplan er sendt og venter på godkjenning.',
      'pay_at_office_option': 'Betal kontant på regnskapskontoret',
      'pay_at_office_subtitle': 'Velg en dato, så varsler vi regnskapskontoret om at du kommer.',
      'pay_at_office_subject': 'Kontant betaling på regnskapskontoret',
      'pay_at_office_description': 'Eieren betaler kontant på regnskapskontoret den',
      'pay_at_office_confirmed': 'Alt er klart — regnskapskontoret vil vente på deg på valgt dato. Det blir en glede å ta imot deg.',
      'per_unit_selection_note': 'Utvalget ditt dekker flere enheter — hver enhet får sin egen separate kvittering.',
      'pay_partial_toggle': 'Betal et delbeløp',
      'pay_partial_amount_label': 'Beløp å betale nå',
      'remaining_due_date_label': 'Restsaldo forfaller innen',
      'pay_partial_cap_note': 'Inntil 5 dager fra i dag. For lengre tid, kontakt regnskapskontoret.',
      'pay_partial_invalid_amount': 'Skriv inn et beløp større enn 0 og ikke mer enn totalsummen.',
      'pay_partial_date_required': 'Velg når du skal betale resten.',
      'pick_date': 'Velg dato',
      'add_installment': 'Legg til avdrag',
      'submit_request': 'Send forespørsel',
      'cancel': 'Avbryt',
      'close_button': 'Lukk',
      'legend_issued': 'Gjeld utstedt',
      'legend_today': 'I dag',
      'legend_selected': 'Valgt',
      'profile_title': 'Profil',
      'settings_title': 'Innstillinger',
      'payment_methods_title': 'Betalingsmetoder',
      'contact_us_title': 'Kontakt oss',
      'about_title': 'Om appen',
      'language_title': 'Språk',
      'role_label': 'Rolle',
      'village_label': 'Landsby',
      'fullname_hint': 'Fullt navn',
      'save_button': 'Lagre',
      'profile_saved': 'Profil oppdatert.',
      'payment_methods_coming_soon': 'Oppsett av nettbetaling pågår. Du vil snart kunne legge til en betalingsmetode her.',
      'contact_us_sent': 'Meldingen din er sendt — vi tar kontakt snart.',
      'contact_us_no_unit': 'Ingen enhet koblet til kontoen din ennå.',
      'load_unit_error': "Kunne ikke laste enheten din. Sjekk tilkoblingen og prøv igjen.",
      'retry_button': "Prøv igjen",
      'contact_us_subject_hint': 'Emne',
      'contact_us_message_hint': 'Meldingen din',
      'about_version': 'Versjon 1.0.0',
      'about_description': 'OwnerConnect hjelper deg med å administrere enheten, avgiftene og forespørslene dine på resortet — alt på ett sted.',
      'notifications_title': 'Varsler',
      'mark_all_read': 'Merk alle som lest',
      'no_notifications_yet': 'Ingen varsler ennå',
      'payment_history_title': 'Betalingshistorikk',
      'download_receipt': 'Last ned kvittering',
      'no_payments_yet': 'Ingen betalinger funnet',
      'receipt_no_label': 'Kvitteringsnr.',
      'filter_by_month': 'Filtrer etter måned',
      'clear_filter': 'Fjern filter',
      'combined_total': 'Samlet utestående beløp',
      'per_unit_breakdown': 'Fordeling per enhet',
      'clearance_title': 'Saldoerklæring',
      'generate_clearance': 'Utsted saldoerklæring',
      'as_of_date': 'Per dato',
      'clearance_clear_status': 'Ingen utestående beløp',
      'clearance_outstanding_status': 'Utestående saldo',
      'clearance_history': 'Tidligere erklæringer',
      'no_clearance_yet': 'Ingen erklæringer ennå',
      'select_unit': 'Velg enhet',
    },
    'zh': {
      'app_title': 'OwnerConnect',
      'charges_title': '单元费用账单',
      'tickets_title': '客户支持与维修',
      'passes_title': '大门与海滩通行证',
      'pay_now': '支付所选费用',
      'create_ticket': '新建支持请求',
      'select_issue_type': '是什么问题？',
      'category_electrician': '电工',
      'category_plumber': '水管工',
      'category_carpenter': '木匠',
      'category_satellite': '卫星技术员',
      'category_gardening': '园艺与农业',
      'category_pest_control': '害虫防治',
      'issue_details_hint': '添加更多详情（可选）',
      'ticket_submitted': '您的请求已提交——我们的团队会尽快与您联系。',
      'create_pass': '新建访客通行证',
      'no_charges': '未找到费用记录',
      'no_tickets': '未找到支持工单',
      'no_passes': '未找到通行证',
      'status_published': '已发布',
      'status_paid': '已支付',
      'status_unpaid': '未支付',
      'unit': '单元',
      'amount': '金额',
      'remaining': '剩余',
      'details': '详情',
      'qr_code': '显示入场二维码',
      'pass_code_label': '代码',
      'splash_tagline': '智能度假村生活，互联互通',
      'splash_checking': '正在检查登录状态…',
      'login_title': '欢迎使用 OwnerConnect',
      'login_subtitle': '选择您的国家并输入手机号码以继续',
      'phone_hint': '手机号码',
      'continue_button': '继续',
      'invalid_phone': '请输入有效的手机号码',
      'dev_bypass_button': '开发者测试登录',
      'otp_title': '验证码',
      'otp_subtitle': '请输入发送至以下号码的 6 位验证码',
      'verify_button': '验证',
      'resend_code': '重新发送验证码',
      'resend_in': '重新发送验证码，剩余',
      'pending_resort_title': '账户尚未关联',
      'pending_resort_message': '您的账户已创建，但尚未关联度假村/社区。请联系您的度假村管理处。',
      'logout': '退出登录',
      'or_divider': '或',
      'or_continue_another_way': '或以其他方式继续',
      'continue_with_google': '使用 Google 继续',
      'continue_with_email': '使用邮箱继续',
      'email_hint': '电子邮箱',
      'password_hint': '密码',
      'sign_in_button': '登录',
      'register_button': '创建账户',
      'toggle_to_register': '还没有账户？立即创建',
      'toggle_to_sign_in': '已有账户？登录',
      'link_account_title': '关联您的账户',
      'link_account_subtitle': '请输入在度假村登记的手机号码和工作人员提供的激活码。',
      'activation_code_hint': '激活码',
      'role_owner': '业主',
      'role_tenant': '租户',
      'checkout_title': '结账',
      'payment_successful': '支付成功',
      'payment_failed': '支付失败',
      'order_id': '订单号',
      'payment_processed_success': '您的付款已成功处理。',
      'payment_options_title': '支付方式',
      'pay_online_option': '在线支付',
      'pay_online_subtitle': '通过支付网关立即用银行卡支付。',
      'defer_option': '延期支付',
      'defer_subtitle': '将到期日延后最多 3 天。',
      'defer_multi_charge_note': '延期和分期计划一次仅可用于一笔费用 — 请选择单笔费用以使用这些功能。',
      'deferred_to_label': '已延期至',
      'payment_plan_option': '申请分期付款计划',
      'payment_plan_subtitle': '为大额款项提出分期方案 — 需要会计审批。',
      'payment_plan_pending': '您的分期付款申请已提交，正在等待会计审批。',
      'pay_at_office_option': '在财务办公室现金支付',
      'pay_at_office_subtitle': '选择一个日期，我们会通知财务办公室您将到访。',
      'pay_at_office_subject': '在财务办公室现金支付',
      'pay_at_office_description': '业主将于以下日期在财务办公室现金支付：',
      'pay_at_office_confirmed': '一切就绪——财务办公室将在您选定的日期恭候您的到来。我们很荣幸能接待您。',
      'per_unit_selection_note': '您的选择涉及多个单元——每个单元将开具各自独立的收据。',
      'pay_partial_toggle': '支付部分金额',
      'pay_partial_amount_label': '现在支付的金额',
      'remaining_due_date_label': '剩余余额到期日',
      'pay_partial_cap_note': '最多可延至今日起 5 天内。如需更长时间，请联系财务办公室。',
      'pay_partial_invalid_amount': '请输入大于 0 且不超过总额的金额。',
      'pay_partial_date_required': '请选择您将支付剩余款项的时间。',
      'pick_date': '选择日期',
      'add_installment': '添加分期',
      'submit_request': '提交申请',
      'cancel': '取消',
      'close_button': '关闭',
      'legend_issued': '欠款已生成',
      'legend_today': '今天',
      'legend_selected': '已选择',
      'profile_title': '个人资料',
      'settings_title': '设置',
      'payment_methods_title': '支付方式',
      'contact_us_title': '联系我们',
      'about_title': '关于',
      'language_title': '语言',
      'role_label': '身份',
      'village_label': '社区',
      'fullname_hint': '姓名',
      'save_button': '保存',
      'profile_saved': '个人资料已更新。',
      'payment_methods_coming_soon': '在线支付功能正在筹备中。您很快就能在此添加支付方式。',
      'contact_us_sent': '您的消息已发送——我们会尽快回复您。',
      'contact_us_no_unit': '您的账户尚未关联任何单元。',
      'load_unit_error': "无法加载您的单元信息,请检查网络连接后重试。",
      'retry_button': "重试",
      'contact_us_subject_hint': '主题',
      'contact_us_message_hint': '您的留言',
      'about_version': '版本 1.0.0',
      'about_description': 'OwnerConnect 帮助您在一个平台上管理您的单元、费用和度假村相关请求。',
      'notifications_title': '通知',
      'mark_all_read': '全部标记为已读',
      'no_notifications_yet': '暂无通知',
      'payment_history_title': '支付记录',
      'download_receipt': '下载收据',
      'no_payments_yet': '未找到支付记录',
      'receipt_no_label': '收据编号',
      'filter_by_month': '按月筛选',
      'clear_filter': '清除筛选',
      'combined_total': '合计应付总额',
      'per_unit_breakdown': '按单元明细',
      'clearance_title': '结清证明',
      'generate_clearance': '开具结清证明',
      'as_of_date': '截至日期',
      'clearance_clear_status': '无欠款',
      'clearance_outstanding_status': '未结余额',
      'clearance_history': '历史证明记录',
      'no_clearance_yet': '暂无结清证明',
      'select_unit': '选择单元',
    },
    'hi': {
      'app_title': 'OwnerConnect',
      'charges_title': 'यूनिट शुल्क और फीस',
      'tickets_title': 'सहायता और रखरखाव',
      'passes_title': 'गेट और बीच पास',
      'pay_now': 'चयनित शुल्क का भुगतान करें',
      'create_ticket': 'नया सहायता अनुरोध',
      'select_issue_type': 'समस्या क्या है?',
      'category_electrician': 'इलेक्ट्रीशियन',
      'category_plumber': 'प्लंबर',
      'category_carpenter': 'बढ़ई',
      'category_satellite': 'सैटेलाइट तकनीशियन',
      'category_gardening': 'बागवानी और कृषि',
      'category_pest_control': 'कीट नियंत्रण',
      'issue_details_hint': 'अधिक विवरण जोड़ें (वैकल्पिक)',
      'ticket_submitted': 'आपका अनुरोध भेज दिया गया है — हमारी टीम जल्द ही आपसे संपर्क करेगी।',
      'create_pass': 'नया विज़िटर पास',
      'no_charges': 'कोई शुल्क नहीं मिला',
      'no_tickets': 'कोई सहायता टिकट नहीं मिला',
      'no_passes': 'कोई गेट पास नहीं मिला',
      'status_published': 'प्रकाशित',
      'status_paid': 'भुगतान किया गया',
      'status_unpaid': 'अवैतनिक',
      'unit': 'यूनिट',
      'amount': 'राशि',
      'remaining': 'शेष',
      'details': 'विवरण',
      'qr_code': 'प्रवेश QR कोड दिखाएं',
      'pass_code_label': 'कोड',
      'splash_tagline': 'स्मार्ट रिज़ॉर्ट जीवन, जुड़ा हुआ',
      'splash_checking': 'आपका सत्र जाँचा जा रहा है…',
      'login_title': 'OwnerConnect में आपका स्वागत है',
      'login_subtitle': 'जारी रखने के लिए अपना देश चुनें और फ़ोन नंबर दर्ज करें',
      'phone_hint': 'फ़ोन नंबर',
      'continue_button': 'जारी रखें',
      'invalid_phone': 'कृपया एक मान्य फ़ोन नंबर दर्ज करें',
      'dev_bypass_button': 'डेवलपर टेस्ट साइन-इन',
      'otp_title': 'सत्यापन कोड',
      'otp_subtitle': 'इस नंबर पर भेजा गया 6-अंकीय कोड दर्ज करें',
      'verify_button': 'सत्यापित करें',
      'resend_code': 'कोड फिर से भेजें',
      'resend_in': 'कोड फिर से भेजा जाएगा',
      'pending_resort_title': 'खाता अभी लिंक नहीं हुआ',
      'pending_resort_message': 'आपका खाता मौजूद है लेकिन अभी तक किसी रिज़ॉर्ट/विलेज से लिंक नहीं है। कृपया अपने रिज़ॉर्ट प्रशासन से संपर्क करें।',
      'logout': 'लॉग आउट',
      'or_divider': 'या',
      'or_continue_another_way': 'या किसी अन्य तरीके से जारी रखें',
      'continue_with_google': 'Google से जारी रखें',
      'continue_with_email': 'ईमेल से जारी रखें',
      'email_hint': 'ईमेल',
      'password_hint': 'पासवर्ड',
      'sign_in_button': 'साइन इन करें',
      'register_button': 'खाता बनाएं',
      'toggle_to_register': 'खाता नहीं है? एक बनाएं',
      'toggle_to_sign_in': 'पहले से खाता है? साइन इन करें',
      'link_account_title': 'अपना खाता लिंक करें',
      'link_account_subtitle': 'अपने रिज़ॉर्ट में दर्ज फ़ोन नंबर और स्टाफ़ द्वारा दिया गया सक्रियण कोड दर्ज करें।',
      'activation_code_hint': 'सक्रियण कोड',
      'role_owner': 'मालिक',
      'role_tenant': 'किरायेदार',
      'checkout_title': 'चेकआउट',
      'payment_successful': 'भुगतान सफल',
      'payment_failed': 'भुगतान विफल',
      'order_id': 'ऑर्डर आईडी',
      'payment_processed_success': 'आपका भुगतान सफलतापूर्वक संसाधित हो गया है।',
      'payment_options_title': 'भुगतान विकल्प',
      'pay_online_option': 'ऑनलाइन भुगतान करें',
      'pay_online_subtitle': 'पेमेंट गेटवे के माध्यम से अभी कार्ड से भुगतान करें।',
      'defer_option': 'भुगतान स्थगित करें',
      'defer_subtitle': 'नियत तारीख को 3 दिनों तक आगे बढ़ाएं।',
      'defer_multi_charge_note': 'स्थगन और भुगतान योजनाएं एक बार में केवल एक शुल्क के लिए उपलब्ध हैं — उपयोग करने के लिए एक ही शुल्क चुनें।',
      'deferred_to_label': 'तक स्थगित',
      'payment_plan_option': 'भुगतान योजना का अनुरोध करें',
      'payment_plan_subtitle': 'बड़ी राशि के लिए किश्तों का प्रस्ताव दें — अकाउंटेंट की मंज़ूरी आवश्यक है।',
      'payment_plan_pending': 'आपका भुगतान योजना अनुरोध सबमिट कर दिया गया है और अकाउंटेंट की मंज़ूरी की प्रतीक्षा में है।',
      'pay_at_office_option': 'अकाउंट्स ऑफिस में नकद भुगतान करें',
      'pay_at_office_subtitle': 'एक तारीख चुनें, हम अकाउंट्स ऑफिस को आपके आने की सूचना देंगे।',
      'pay_at_office_subject': 'अकाउंट्स ऑफिस में नकद भुगतान',
      'pay_at_office_description': 'मालिक इस दिन अकाउंट्स ऑफिस में नकद भुगतान करेंगे:',
      'pay_at_office_confirmed': 'सब तैयार है — अकाउंट्स ऑफिस आपकी चुनी हुई तारीख पर प्रतीक्षा करेगा। आपका स्वागत करना हमारे लिए खुशी की बात होगी।',
      'per_unit_selection_note': 'आपका चयन एक से अधिक यूनिट को कवर करता है — प्रत्येक यूनिट को अपनी अलग रसीद मिलेगी।',
      'pay_partial_toggle': 'आंशिक राशि का भुगतान करें',
      'pay_partial_amount_label': 'अभी भुगतान की जाने वाली राशि',
      'remaining_due_date_label': 'शेष राशि की देय तिथि',
      'pay_partial_cap_note': 'आज से अधिकतम 5 दिनों तक। अधिक समय के लिए अकाउंट्स ऑफिस से संपर्क करें।',
      'pay_partial_invalid_amount': '0 से अधिक और कुल राशि से अधिक न हो, ऐसी राशि दर्ज करें।',
      'pay_partial_date_required': 'चुनें कि आप शेष राशि कब भुगतान करेंगे।',
      'pick_date': 'तारीख चुनें',
      'add_installment': 'किश्त जोड़ें',
      'submit_request': 'अनुरोध भेजें',
      'cancel': 'रद्द करें',
      'close_button': 'बंद करें',
      'legend_issued': 'देय राशि जारी',
      'legend_today': 'आज',
      'legend_selected': 'चयनित',
      'profile_title': 'प्रोफ़ाइल',
      'settings_title': 'सेटिंग्स',
      'payment_methods_title': 'भुगतान के तरीके',
      'contact_us_title': 'संपर्क करें',
      'about_title': 'ऐप के बारे में',
      'language_title': 'भाषा',
      'role_label': 'भूमिका',
      'village_label': 'विलेज',
      'fullname_hint': 'पूरा नाम',
      'save_button': 'सहेजें',
      'profile_saved': 'प्रोफ़ाइल अपडेट हो गई।',
      'payment_methods_coming_soon': 'ऑनलाइन भुगतान सेटअप प्रगति पर है। आप जल्द ही यहाँ भुगतान का तरीका जोड़ सकेंगे।',
      'contact_us_sent': 'आपका संदेश भेज दिया गया है — हम जल्द ही आपसे संपर्क करेंगे।',
      'contact_us_no_unit': 'आपके खाते से अभी तक कोई यूनिट लिंक नहीं है।',
      'load_unit_error': "आपकी यूनिट लोड नहीं हो सकी। कृपया कनेक्शन जांचें और फिर से प्रयास करें।",
      'retry_button': "पुनः प्रयास करें",
      'contact_us_subject_hint': 'विषय',
      'contact_us_message_hint': 'आपका संदेश',
      'about_version': 'संस्करण 1.0.0',
      'about_description': 'OwnerConnect आपको अपने रिज़ॉर्ट में अपनी यूनिट, शुल्क और अनुरोधों को एक ही जगह प्रबंधित करने में मदद करता है।',
      'notifications_title': 'सूचनाएं',
      'mark_all_read': 'सभी को पढ़ा हुआ चिह्नित करें',
      'no_notifications_yet': 'अभी तक कोई सूचना नहीं',
      'payment_history_title': 'भुगतान इतिहास',
      'download_receipt': 'रसीद डाउनलोड करें',
      'no_payments_yet': 'कोई भुगतान नहीं मिला',
      'receipt_no_label': 'रसीद संख्या',
      'filter_by_month': 'महीने के अनुसार फ़िल्टर करें',
      'clear_filter': 'फ़िल्टर हटाएं',
      'combined_total': 'संयुक्त कुल देय राशि',
      'per_unit_breakdown': 'यूनिट के अनुसार विवरण',
      'clearance_title': 'क्लीयरेंस स्टेटमेंट',
      'generate_clearance': 'क्लीयरेंस स्टेटमेंट जारी करें',
      'as_of_date': 'इस तारीख तक',
      'clearance_clear_status': 'कोई बकाया देय राशि नहीं',
      'clearance_outstanding_status': 'बकाया शेष राशि',
      'clearance_history': 'पिछले स्टेटमेंट',
      'no_clearance_yet': 'अभी तक कोई क्लीयरेंस स्टेटमेंट नहीं',
      'select_unit': 'यूनिट चुनें',
    },
    'ja': {
      'app_title': 'OwnerConnect',
      'charges_title': 'ユニットの請求・料金',
      'tickets_title': 'サポート・メンテナンス',
      'passes_title': 'ゲート・ビーチパス',
      'pay_now': '選択した請求を支払う',
      'create_ticket': '新規サポート依頼',
      'select_issue_type': 'どのようなご用件ですか？',
      'category_electrician': '電気技師',
      'category_plumber': '配管工',
      'category_carpenter': '大工',
      'category_satellite': '衛星アンテナ技術者',
      'category_gardening': '造園・農業',
      'category_pest_control': '害虫駆除',
      'issue_details_hint': '詳細を追加（任意）',
      'ticket_submitted': 'リクエストを送信しました — 担当チームより間もなくご連絡します。',
      'create_pass': '新規訪問者パス',
      'no_charges': '請求が見つかりません',
      'no_tickets': 'サポートチケットが見つかりません',
      'no_passes': 'パスが見つかりません',
      'status_published': '公開済み',
      'status_paid': '支払い済み',
      'status_unpaid': '未払い',
      'unit': 'ユニット',
      'amount': '金額',
      'remaining': '残額',
      'details': '詳細',
      'qr_code': '入場用QRコードを表示',
      'pass_code_label': 'コード',
      'splash_tagline': 'スマートなリゾートライフ、つながる',
      'splash_checking': 'セッションを確認しています…',
      'login_title': 'OwnerConnectへようこそ',
      'login_subtitle': '続けるには国を選択し、電話番号を入力してください',
      'phone_hint': '電話番号',
      'continue_button': '続ける',
      'invalid_phone': '有効な電話番号を入力してください',
      'dev_bypass_button': '開発者テストログイン',
      'otp_title': '確認コード',
      'otp_subtitle': '次の番号に送信された6桁のコードを入力してください',
      'verify_button': '確認',
      'resend_code': 'コードを再送信',
      'resend_in': 'コードの再送信まで',
      'pending_resort_title': 'アカウント未連携',
      'pending_resort_message': 'アカウントは作成されていますが、まだリゾート／村に連携されていません。リゾートの管理者にお問い合わせください。',
      'logout': 'ログアウト',
      'or_divider': 'または',
      'or_continue_another_way': 'または他の方法で続ける',
      'continue_with_google': 'Googleで続ける',
      'continue_with_email': 'メールで続ける',
      'email_hint': 'メールアドレス',
      'password_hint': 'パスワード',
      'sign_in_button': 'サインイン',
      'register_button': 'アカウントを作成',
      'toggle_to_register': 'アカウントをお持ちでないですか？作成する',
      'toggle_to_sign_in': 'すでにアカウントをお持ちですか？サインイン',
      'link_account_title': 'アカウントを連携',
      'link_account_subtitle': 'リゾートに登録済みの電話番号と、スタッフから受け取った有効化コードを入力してください。',
      'activation_code_hint': '有効化コード',
      'role_owner': 'オーナー',
      'role_tenant': '入居者',
      'checkout_title': 'チェックアウト',
      'payment_successful': '支払いが完了しました',
      'payment_failed': '支払いに失敗しました',
      'order_id': '注文ID',
      'payment_processed_success': 'お支払いが正常に処理されました。',
      'payment_options_title': '支払い方法',
      'pay_online_option': 'オンラインで支払う',
      'pay_online_subtitle': '決済ゲートウェイ経由でカードにて今すぐ支払う。',
      'defer_option': '支払いを延期する',
      'defer_subtitle': '支払期日を最大3日延期します。',
      'defer_multi_charge_note': '延期と分割払いプランは、一度に1件の請求のみに利用できます — 利用するには1件の請求を選択してください。',
      'deferred_to_label': '延期先',
      'payment_plan_option': '分割払いプランを申請',
      'payment_plan_subtitle': '高額な支払いの分割案を提案します — 会計担当者の承認が必要です。',
      'payment_plan_pending': '分割払いプランの申請が送信され、会計担当者の承認待ちです。',
      'pay_at_office_option': '経理オフィスで現金払い',
      'pay_at_office_subtitle': '日付を選択すると、経理オフィスにご来訪を通知します。',
      'pay_at_office_subject': '経理オフィスでの現金支払い',
      'pay_at_office_description': 'オーナーは次の日に経理オフィスで現金払いを行います：',
      'pay_at_office_confirmed': '準備完了です — 経理オフィスは選択された日にお待ちしております。お迎えできることを嬉しく思います。',
      'per_unit_selection_note': '選択内容は複数のユニットにまたがっています — 各ユニットに個別の領収書が発行されます。',
      'pay_partial_toggle': '一部の金額を支払う',
      'pay_partial_amount_label': '今回支払う金額',
      'remaining_due_date_label': '残額の支払期限',
      'pay_partial_cap_note': '本日から最大5日間。それ以上の場合は経理オフィスにお問い合わせください。',
      'pay_partial_invalid_amount': '0より大きく、合計金額を超えない金額を入力してください。',
      'pay_partial_date_required': '残額をいつ支払うか選択してください。',
      'pick_date': '日付を選択',
      'add_installment': '分割を追加',
      'submit_request': '申請を送信',
      'cancel': 'キャンセル',
      'close_button': '閉じる',
      'legend_issued': '請求発生日',
      'legend_today': '今日',
      'legend_selected': '選択中',
      'profile_title': 'プロフィール',
      'settings_title': '設定',
      'payment_methods_title': '支払い方法',
      'contact_us_title': 'お問い合わせ',
      'about_title': 'アプリについて',
      'language_title': '言語',
      'role_label': '区分',
      'village_label': '村',
      'fullname_hint': '氏名',
      'save_button': '保存',
      'profile_saved': 'プロフィールを更新しました。',
      'payment_methods_coming_soon': 'オンライン決済の設定を準備中です。まもなくここで支払い方法を追加できるようになります。',
      'contact_us_sent': 'メッセージを送信しました — 追ってご連絡いたします。',
      'contact_us_no_unit': 'アカウントにまだユニットが連携されていません。',
      'load_unit_error': "ユニット情報を読み込めませんでした。接続を確認してもう一度お試しください。",
      'retry_button': "再試行",
      'contact_us_subject_hint': '件名',
      'contact_us_message_hint': 'メッセージ',
      'about_version': 'バージョン 1.0.0',
      'about_description': 'OwnerConnectは、リゾートでのユニット、請求、依頼の管理を一か所でサポートします。',
      'notifications_title': '通知',
      'mark_all_read': 'すべて既読にする',
      'no_notifications_yet': 'まだ通知はありません',
      'payment_history_title': '支払い履歴',
      'download_receipt': '領収書をダウンロード',
      'no_payments_yet': '支払い記録が見つかりません',
      'receipt_no_label': '領収書番号',
      'filter_by_month': '月で絞り込む',
      'clear_filter': 'フィルターを解除',
      'combined_total': '合計未払い額',
      'per_unit_breakdown': 'ユニット別内訳',
      'clearance_title': '清算証明書',
      'generate_clearance': '清算証明書を発行',
      'as_of_date': '基準日',
      'clearance_clear_status': '未払いはありません',
      'clearance_outstanding_status': '未払い残高',
      'clearance_history': '過去の証明書',
      'no_clearance_yet': 'まだ証明書はありません',
      'select_unit': 'ユニットを選択',
    },
  };

  String translate(String key) {
    final table = _localizedValues[locale.languageCode];
    return table?[key] ?? _localizedValues['en']![key] ?? key;
  }
}

/// Languages this app ships full translations for. The app opens in the
/// device's own system language when it's one of these; otherwise it falls
/// back to English rather than forcing Arabic on a non-Arabic, non-English
/// owner — see LocaleBloc._resolveDeviceLanguageCode.
const List<Locale> kSupportedLocales = [
  Locale('en'),
  Locale('ar'),
  Locale('de'),
  Locale('fr'),
  Locale('it'),
  Locale('ru'),
  Locale('uk'),
  Locale('fi'),
  Locale('nb'),
  Locale('zh'),
  Locale('hi'),
  Locale('ja'),
];

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      kSupportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
